### ISSUE TITLE
ZSH auto completion

### ISSUE THREAD

**Issue by 1mm0rt41PC** [cheat/cheat#130]
Auto completion in zsh doesn't work.
I need to do sudo cp /usr/share/zsh/site-functions/\* /usr/local/share/zsh/site-functions/
After that it work.

**Comment by Marcel-Robitaille** [comment]
I have tried putting cheat.zsh in a folder in FPATH with no luck. Can someone help me?

**Comment by gotbletu** [comment]
Tryed all the above but nothing worked.

So I wrote one myself, hope this helps anyone looking at this page in the future =)

    # cheat autocompletion; just add to ~/.zshrc
    _cmpl_cheat() {
	reply=($(cheat -l | cut -d' ' -f1))
    }
    compctl -K _cmpl_cheat cheat

**Comment by iNoSec** [comment]
Thanks @gotbletu I tried so many things and i added your script to my .zshrc, now i have this autocompletion work like a charm on cheat!!!

**Comment by AmauryOrtega** [comment]
Thanks @gotbletu, it works like a charm

**Comment by roachsinai** [comment]
In fact, the name of autocomplete file stored at /usr/share/zsh/site-functions/ must begin with `_` for Zsh, so you have to change `cheat` in this repo to `_cheat`. Then it workd.
