### ISSUE TITLE
Can't find autocompletion file

### ISSUE THREAD

**Issue by rightaway** [cheat/cheat#213]
When installing on Ubuntu using 'sudo pip install cheat' to get latest 2.1.7, in `/usr/local/lib/python2.7/dist-packages/cheat/` I can't see any autocompletion directory to get the cheat.zsh file. Where is this file to be found when installing from pip?

**Comment by Akasurde** [comment]
Currently, pip does not install auto-completion by default, refer [this](https://github.com/chrisallenlane/cheat#enabling-command-line-autocompletion) 

As per your distro refer installation method.

**Comment by chrisallenlane** [comment]
Autocompletion was always a mess in the prior version of `cheat`. With the Go rewrite (#470), the current priority is to get this right. Feel free to track the progress here: #476.
