### ISSUE TITLE
edit not working without hack on windows

### ISSUE THREAD

**Issue by ipstone** [cheat/cheat#247]
Hello, I just checked out the current version of cheat: b6137ca, code base is really nice. However, subprocess.call doesn't work out of box on windows (python 2.7.6). But hacking the following lines:
changing the editor call from [ ... ] to a string , it works.  

Maybe it's just an edge case, but it would be nice if possible to include a fix, so it works out of box. Thanks

def create(sheet):
    """ Creates a cheatsheet """
    new_sheet_path = os.path.join(sheets.default_path(), sheet)

```
try:
    subprocess.call(editor() + " "+ new_sheet_path)

except OSError:
    die('Could not launch ' + editor())
```

def edit(sheet):
    """ Opens a cheatsheet for editing """

```
try:
    subprocess.call(editor() + " "+ path(sheet))

except OSError:
    die('Could not launch ' + editor())
```

**Comment by chid** [comment]
It sounds like the issue is not with that call but potentially how the arguments are escaped. I also think this proposed change will break on Linux

From the docs. 

```args is required for all calls and should be a string, or a sequence of program arguments. Providing a sequence of arguments is generally preferred, as it allows the module to take care of any required escaping and quoting of arguments (e.g. to permit spaces in file names). If passing a single string, either shell must be True (see below) or else the string must simply name the program to be executed without specifying any arguments.```

**Comment by chrisallenlane** [comment]
I just released `cheat` v3, which was an entire re-write from scratch in Go. That being the case, this should now be resolved. Please upgrade to the newest version, and let me know if you encounter any errors.
