### ISSUE TITLE
Better search result output?

### ISSUE THREAD

**Issue by gotbletu** [cheat/cheat#260]
Could you make the search results output the "block of code" since most of the time we are searching for the commented out text and that is all it outputs, which isnt very useful.

example:
cheat -s integers

```
awk:
  # sum integers from a file or stdin, one integer per line:
  # using specific character as separator to sum integers from a file or stdin
```

So we would have to waste more time pulling out the awk cheatsheet

cheat awk

```
# sum integers from a file or stdin, one integer per line:
printf '1\n2\n3\n' | awk '{ sum += $1} END {print sum}'

# using specific character as separator to sum integers from a file or stdin
printf '1:2:3' | awk -F ":" '{print $1+$2+$3}'

# print a multiplication table
seq 9 | sed 'H;g' | awk -v RS='' '{for(i=1;i<=NF;i++)printf("%dx%d=%d%s", i, NR, i*NR, i==NR?"\n":"\t")}'

# Specify output separator character
printf '1 2 3' | awk 'BEGIN {OFS=":"}; {print $1,$2,$3}'
```

**Comment by chrisallenlane** [comment]
Hi, @gotbletu 

Thanks for your patience on this one. `cheat`'s search mechanism has been substandard for a while.

Please upgrade to `v3.6.0`. The search is now significantly improved:
https://github.com/cheat/cheat/releases/tag/3.6.0

As of `3.6.0`:
- It's now possible to constrain searches to an individual cheatsheet. Ie, `cheat tar -s extract` will search for `extract` only within the `tar` cheatsheet.
- The formatting of the search output has been changed to mirror what you advised above. This spares you the need to open a cheatsheet after locating it with a search.
- The (mostly pointless) red highlighting on matched search terms has been deprecated. In its place, syntax highlighting is now applied to all match results instead.

Please let me know if you encounter any issues. Thanks.

Closing as resolved.
