### ISSUE TITLE
Missing man page

### ISSUE THREAD

**Issue by pirat89** [cheat/cheat#272]
Yes, usage is trivial, however it could be fine to have manpage.

**Comment by mblarsen** [comment]
and/or #306

**Comment by pirat89** [comment]
@mblarsen both could be used :-) that sounds like good idea.

**Comment by chrisallenlane** [comment]
Just a bump: I want to get the shell integration improved first, but after that, this moves up the priority list. I really want to nail down the packaging details now, and having a proper manpage is certainly part of that.

**Comment by chrisallenlane** [comment]
This is resolved with `3.8.0`:
https://github.com/cheat/cheat/releases/tag/3.8.0

Package maintainers: where possible, please install `doc/cheat.1` to whichever `MANPATH` is appropriate for your packager. Thanks!
