### ISSUE TITLE
Syntax Highlight Issue only partially working 

### ISSUE THREAD

**Issue by LarryCheech** [cheat/cheat#298]
Hay 

I am having an issue getting syntax highlighting to working, everything has installed fine but there is only partial syntax highlight

This is my bashrc

``` sh
# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
 export LS_OPTIONS='--color=auto'
 eval "`dircolors`"
 alias ls='ls $LS_OPTIONS'
 alias ll='ls $LS_OPTIONS -l'
 alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
 alias rm='rm -i'
 alias cp='cp -i'
 alias mv='mv -i'

export EDITOR=/usr/bin/nano
export CHEATCOLORS=true
```

**Comment by chrisallenlane** [comment]
The relevant code has been extensively re-written since this ticket was opened (sorry it took so long for me to reply), so I'm going to close this as resolved. If you continue to experience a problem after updating `cheat`, please re-open this ticket. Thanks.
