### ISSUE TITLE
multi-word $EDITOR value does not work

### ISSUE THREAD

**Issue by rski** [cheat/cheat#301]
When cheat spawns the EDITOR, it assumes that EDITOR is one word. In my environment EDITOR='emacsclient -c', so it fails. 
I've hacked it together for my environment so that cheat.edit() and cheat.create() work. It needs a bit of a cleaner implementation and to make sure that it doesn't break anything, I'll think I'll fix it over the weekend.

**Comment by GFdevelop** [comment]
@rski @chrisallenlane this issue exist in zsh:
```
failed to edit cheatsheet: exec: "geany -ims": executable file not found in $PATH
```
see also: https://superuser.com/questions/521070/unix-environment-variables-with-arguments

**Comment by chrisallenlane** [comment]
Thanks for the info, @GFdevelop. I have re-opened this ticket and will take a look.

**Comment by chrisallenlane** [comment]
@GFdevelop, please try the `3.5.1` release. I'm pretty confident that it will solve your problem:

https://github.com/cheat/cheat/releases/tag/3.5.1

If it doesn't, please re-open this ticket. Thanks.

**Comment by GFdevelop** [comment]
@chrisallenlane you solved the problem, pretty good job :+1:
