### ISSUE TITLE
pip installation of cheat on windows has no cheat.exe or cheat.bat produced.

### ISSUE THREAD

**Issue by ipstone** [cheat/cheat#305]
Somehow when I pip installed cheat on windows, there is only a *nix style cheat file created (with #! line for python interpreter), but there is no cheat.exe or cheat.bat created. 

Is this something we can setup/configure properly for cheat (on windows)?

Thanks

**Comment by ipstone** [comment]
Hi, I somehow created a bat file, just run the following inside:
"""@echo off
...path\python.exe ..path\cheat %*
"""

After putting this bat file in the Scripts folder (where the cheat python file is), the at command line , cheat (command would work).

Using the bat file also have the benefits that the EDITOR environment variable can be added in the bat file, as well as cheat folder path etc.

Not sure if this is a standard solution on windows, but it currently works while for my user case.

Thanks

**Comment by chrisallenlane** [comment]
I have zero experience with Python on Windows (or any scripting on Windows at all, really), but if somebody from the community is able to produce a pull-request, I would gladly merge it in.

**Comment by aroonav** [comment]
Hi @chrisallenlane. I have created a PR for this issue.
I have created a batch script named cheat.bat which should be in the same directory as the cheat python script. The batch script will get executed when cheat is called from a non-bash command prompt in windows which will execute the cheat python script.

Please review. Tell me if you need any modifications :)

**Comment by roachsinai** [comment]
I installed cheat use pip on Win10, but cheat not work. So any update?

**Comment by chrisallenlane** [comment]
Thanks for bringing this to my attention, guys, and thanks @aroonav for your pull-request.

I honestly have no idea how to even use Python on Windows, as I haven't used meaningfully used Windows for like 12 years. With that said, I've flagged this as Priority as a reminder to figure out how to set up a test-environment in the near term. I'll update the ticket when I have new information.

**Comment by roachsinai** [comment]
Also an alternative that if on Windows 10 could install and use cheat on wsl.

**Comment by chrisallenlane** [comment]
I just merged #361, which should resolve this. I'll push it out with `cheat` version `2.5.1` later in a few hours.

I'll close this for now. Please re-test on cheat 2.5.1, and re-open this ticket if there's still an issue.

Thanks.
