### ISSUE TITLE
Make cheats organizable in sub-directories

### ISSUE THREAD

**Issue by kenanpelit** [cheat/cheat#315]
Sounds like a good idea. What do you say?
https://github.com/havan/cheat/commit/8526d4012d69f3cd319b24706cd8708d86bb4b96

**Comment by chrisallenlane** [comment]
This is under heavy consideration. I just need to figure out how nicely this will play with other features that are currently in the works, given that this will (probably?) require some non-trivial rewriting of the application.

**Comment by kapad** [comment]
I was looking to see if there was any issue that suggested moving the cheats directory that you have here into a separate repo. 
I want to track my ~/.cheats in a separate repo, but also want to be able to easily compare it with the cheats that you have (it's like a central repository, but I will have my own custom files, and maybe some changes in some file).

**Comment by kapad** [comment]
Making cheats into sub directories, I think would let me do this even better. But, then there's the case where I have the same cheat in two directories. What's the default, and what's the custom one. How are the appended?

**Comment by chrisallenlane** [comment]
This is now supported with `cheat` v3, which was released moments ago. Please upgrade and try it out.

Community cheatsheets are now hosted here:

https://github.com/cheat/cheatsheets
