### ISSUE TITLE
Proposal: implement --global flag

### ISSUE THREAD

**Issue by chrisallenlane** [cheat/cheat#322]
By default, when a user has both user-defined and global (ie, package-provided) cheatsheets for a term, `cheat` displays only the user-defined cheatsheet. This effectively "masks" the package-provided cheatsheets, making them impossible to view without first deleting the user-defined file.

This is unfortunate, because package-provided cheatsheets are frequently improved upon by the community.

Some users (#262, #296) have asked for a solution to this problem. I would like to propose a solution here and open it up to community discussion.

I propose that we add a `-g` (`--global`) flag that, when used, causes `cheat` to ignore user-defined cheatsheets. For example, if I have a user-defined cheatsheet for `tar`, I may view it with:

```sh
cheat tar
```

If, however, I preferred to view the "global" cheatsheet instead, I may run:

```sh
cheat tar --global
```

I could then manually reconcile the two files via my preferred text-editor as desired.

Please leave feedback on this proposal. If I don't receive negative feedback, I'll try to implement this in the near-term.

**Comment by SRGOM** [comment]
I usually strip the cheatsheet to only contain things that I find useful, e.g.

This is my vim cheatsheet: 

```

#View variables: 
echo a:x
echo g:y
echo &setting
echo @register

#Use vim as pager
vim - 

#Multiple vim commands from command line
vim -c ':VCSVimDiff' -c ':q' -c ':q' myFile

```

But if you look at the global vim cheatsheet, I will not be able to derive any use from its updates because all I'll see would be a very long file.

-------
If I were to propose something- I'd propose checking out http://www.catb.org/~esr/src/.
This is a single file version control. I'd suggest keeping all the individual tips file individually version controlled using this. 

```
#On your side
vim python #changes
src add python
src commit
vim python #changes
src commit
vim python #changes
src commit
#Push out .src/python,v for your users
```

```
#On user side.
cheat -g python
#In background cheat will compare user's python,v against the latest pushed python,v and show the differences in plain format to user (without version control stuff) And will also show what he added on top of his old python,v 

This is a rough outline but I think something along these lines would be better than no global/or raw global.

**Comment by chrisallenlane** [comment]
Closing as resolved with the `v3` release.
