### ISSUE TITLE
Create a separate repo for the cheatsheets?

### ISSUE THREAD

**Issue by dufferzafar** [cheat/cheat#332]
I'm not sure if we've had this discussion before but I feel that the cheatsheets should be decoupled from the python application into a separate repo. I saw another tool today in the same space (http://cheat.sh/) which is using the sheets from this repo. 

I think De-coupling will help such tools.

**Comment by gentb** [comment]
Allowing for import of cheatsheets from https://github.com/rstacruz/cheatsheets might also be nice. There's quite a bit of crossover however so this would require a merge with some fuzzy de-dupe.

**Comment by chrisallenlane** [comment]
Closing this as resolved with `cheat` v3, which was released moments ago.

Community-sourced cheatsheets have been externalized to this repository:
https://github.com/cheat/cheatsheets
