### ISSUE TITLE
Edit multiple files

### ISSUE THREAD

**Issue by Chinggis6** [cheat/cheat#335]
`cheat -e cisco.md ftp.md` results in:

```
> cheat -e cisco.md ftp.md
Usage:
  cheat <cheatsheet>
  cheat -e <cheatsheet>
  cheat -s <keyword>
  cheat -l
  cheat -d
  cheat -v
```
it could open two files at the same time in two separate tabs with `vim -p`, which would be very useful to view and edit multiple cheatsheets.

Thanks for consideration.

**Comment by chrisallenlane** [comment]
This was a good idea, but I'm not confident that I can do this in a cross-platform way without causing more problems, so I'm going to close this ticket. Sorry I'm not able to get this implemented.
