### ISSUE TITLE
Proposal: Print output in pager

### ISSUE THREAD

**Issue by gioulisapo** [cheat/cheat#346]
I have found it very convenient to print the output of cheat in a less-like pager enabling me to have longer cheats without  having to fill my terminal with long outputs. It also enables me to use the pager to search through the cheat-sheet more easily.

In my local installation to achieve that, in the **utils.py** file I added the import of `pydoc`
and in the colorise method I commented out `return highlight(sheet_content, lexer, TerminalFormatter())` and then added `pydoc.pager(highlight(sheet_content, lexer, TerminalFormatter()))`

**Comment by chrisallenlane** [comment]
Question: what is the advantage of building this functionality into `cheat` versus piping `cheat`'s output into `less`? I fear we may be re-inventing the wheel if we go this route.

**Comment by chrisallenlane** [comment]
Going to close this one for now. Feel free to re-open it if there's more to discuss.
