### ISSUE TITLE
licensing contradiction

### ISSUE THREAD

**Issue by tony** [cheat/cheat#347]
I think it's a bit of an old fad, but dual licensing doesn't make much sense. jQuery did it and all of a sudden projects came after dual-licensing. [They ended up backing out of it](https://blog.jquery.com/2012/09/10/jquery-licensing-changes/).

There's no benefit to using GPL as a license if the user can just pick MIT. There's no point in keeping an MIT license if the provisions of GPL are active. It's best to go with one or the other.

**Comment by chrisallenlane** [comment]
Yeah, the licensing situation is pretty stupid currently. With the Go rewrite (#470), however, we have an opportunity to fix this.

I've created a ticket about this (#477), and I'm going to close this ticket in favor of that one. If you have an opinion on the matter, feel free to voice it there. I'm actively soliciting opinions at the moment. Thanks.
