### ISSUE TITLE
Pygments for light-BG terminals

### ISSUE THREAD

**Issue by michaelblyons** [cheat/cheat#349]
If [this line][1] could optionally add `bg='dark'` to [`TerminalFormatter()`][2], I'd appreciate it very much.

As it stands now, I can't see comments when I try to use `CHEATCOLORS`. The contrast against my terminal emulator is just too small.

[1]: https://github.com/chrisallenlane/cheat/blob/edd7b5e806d6d3fcd95c5d091044aaa610a3b4dd/cheat/utils.py#L32
[2]: http://pygments.org/docs/formatters/#TerminalFormatter

**Comment by chrisallenlane** [comment]
Thanks for bringing this to my attention. I'll address this in the near-term.

**Comment by chrisallenlane** [comment]
Closing this as resolved with #427 

@michaelblyons, I'll be publishing `cheat` version `2.5.0` later today. It includes a patch that will allow you to export a `CHEAT_COLORSCHEME` envvar. Export that as `dark`, and you should be all set.
