### ISSUE TITLE
We should not be advocating the use of `sudo pip` in the README

### ISSUE THREAD

**Issue by shanahanjrs** [cheat/cheat#351]
https://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip/21056000#21056000

This can be dangerous and also install packages with the wrong user/permissions. Either pip was installed incorrectly or they need to use `--user`.

**Comment by Tonus1** [comment]
It's a good idea to start with virtualenv... 
Maybe worth a link to... The cheatsheet. 

Adding an example for installing Cheat would worth it :
mkdir cheat 
virtualenv cheat
cd cheat 
./bin/pip install cheat 

Run with ./bin/cheat

**Comment by chrisallenlane** [comment]
@shanahanjrs 

FYI, I just opened #432, which attempts to resolve multiple installation issues. Along with those changes, I updated the `README` to advocate the use of the `--user` flag:

https://github.com/cheat/cheat/pull/432/commits/482161f8e982fc533aabadbb5a6479eb9e794078#diff-04c6e90faac2675aa89e2176d2eec7d8

Does that approach seem sensible?

**Comment by shanahanjrs** [comment]
@chrisallenlane Looks great!

**Comment by chrisallenlane** [comment]
Thanks. This should get merged in soon.
