### ISSUE TITLE
option to show local cheatsheets only 

### ISSUE THREAD

**Issue by drcharlieroot** [cheat/cheat#380]
smth. like `cheat -L` to show only the 'local' cheatsheets kept in `DEFAULT_CHEAT_DIR`

so the user doesn't have to `grep` for `~/.cheat` on most cases

and maybe also including cheatsheets in `CHEATPATH`, if used (when dividing cheatsheets into directories)

**Comment by chrisallenlane** [comment]
+1 for this idea. I'll try to get the corresponding PR merged in within the next few days.

**Comment by chrisallenlane** [comment]
Closing as resolved with the `v3` release. Please upgrade and try it out.
