### ISSUE TITLE
patching the function for autocompletion

### ISSUE THREAD

**Issue by manmio** [cheat/cheat#381]
autocompletion does not work for me in my bash. 
After patching the function from
`cheat -l | cut -d' ' -f1`
to
`cheat -L | cut -d'/' -f5`
autocompltion works fine for me.

**Comment by chrisallenlane** [comment]
With the Go rewrite (#470), this will no longer work. Implementing proper shell integration is a high priority now, though - see #476. There should be some integration updates coming over the next few days.
