### ISSUE TITLE
autocomplete documentation could be more helpful

### ISSUE THREAD

**Issue by sdondley** [cheat/cheat#390]
I don't know much about bash so some more useful hints as to how to get autocomplete working would be appreciated so I can take a more educated guess as to how to implement.

Currently, it tells you to copy the script to "the appropriate path."

What ended up doing to get it to work was to drop the code in the script into my `.bash_profile` configuration file. I have no idea if this is the recommended way of handling this script. It sounds like it should probably go in some directory somewhere.

**Comment by AmauryOrtega** [comment]
Issue #130 is a great example of why autocomplete documentation needs to be improved

**Comment by chrisallenlane** [comment]
I'm going to close this issue now, due to the v3 rewrite into Go (#470 for context). Shell integration is, frankly, still rather poor at the moment, though that's a priority now. Keep you eyes open for a few releases over the next few days for improvements.
