### ISSUE TITLE
Pypi page has no Project Description

### ISSUE THREAD

**Issue by shanahanjrs** [cheat/cheat#437]
When viewing the project on https://pypi.org/project/cheat/ the main content of the page just says 

`Project description`
`The author of this package has not provided a project description`

This can be fixed by providing a `long_description` in the setup.py, usually by reading in the contents of the README file -- https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata

**Comment by chrisallenlane** [comment]
@shanahanjrs 

Thanks for taking a stab at this. This has been annoying me for a while.

Question: I merged this locally and tested it out on my build machine. When I attempt to install, I get the following error:

```
vagrant@ubuntu-bionic:/vagrant$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    with open(os.path.join(here, 'README.md'), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```

Is this a Python 2/3 compatibility error, perhaps?

On my build machine:

```
vagrant@ubuntu-bionic:/vagrant$ python --version
Python 2.7.15+
```

**Comment by shanahanjrs** [comment]
Yes that is, I tested this in Python3 when I wrote it, good catch... Ill Fix it as soon as i have time.

**Comment by shanahanjrs** [comment]
Updated. You should be able to pull the branch again and it will work

**Comment by gnumoksha** [comment]
This project is now written in Go, so I think this issue is not relevant anymore. The description on Pypi may be changed, like:

> ~~cheat allows you to create and view interactive cheatsheets on the command-line. It was designed to help remind *nix system administrators of options for commands that they use frequently, but not frequently enough to remember.~~

> cheat is now written is Go. Refer to https://github.com/cheat/cheat#installing in order to install it.
