### ISSUE TITLE
Adding the choice of Pygments style

### ISSUE THREAD

**Issue by chietsuki** [cheat/cheat#439]
Hi,

If you're using [Terminal256Formatter()](http://pygments.org/docs/formatters/#Terminal256Formatter) instead of [TerminalFormatter()](http://pygments.org/docs/formatters/#TerminalFormatter) in [this line](https://github.com/cheat/cheat/blob/5487314676672039fd014d68b7eea7c261a60b20/cheat/colorize.py#L65) with the parameter ```style``` instead of ```bg```, and set ```'default'``` as default value in [this line](https://github.com/cheat/cheat/blob/5487314676672039fd014d68b7eea7c261a60b20/cheat/configuration.py#L48) and [this line](https://github.com/cheat/cheat/blob/5487314676672039fd014d68b7eea7c261a60b20/config/cheat#L3) we could change the Pygments style with ```CHEAT_COLORSCHEME```.

You can see the different styles [here](https://help.farbox.com/pygments.html).

It could be useful for everyone if we can adapt the syntax color with our terminal.

**Comment by chrisallenlane** [comment]
Hi, @chietsuki 

I just released `cheat` v3, which re-implements this project from scratch in Go. The feature you requested is now available there, thanks to the wonderful [Chroma][] library. Please upgrade and give it a try. Thanks.

[Chroma]: https://github.com/alecthomas/chroma
