### ISSUE TITLE
cheat is unable to find the cheatsheets when installed as user (pip install --user)

### ISSUE THREAD

**Issue by vaz-ar** [cheat/cheat#442]
Hello,
I just noticed that when installed via pip for a user (pip install --user cheat), cheat is unable to find the cheatsheets.

the result of `cheat -d` is:

~~~
$ cheat -d  
/home/my_user/.cheat
/usr/share/cheat
~~~

`/usr/share/cheat` does not exists as cheat was installed locally.

I also cannot find the `cheatsheets` folder under `~/.local/lib/python3.x`

If I missed something or you need more informations let me know.

**Comment by pirat89** [comment]
Not sure how the installation exactly will end now. But in case you don't have created config file automaticaly on the user level, just create it and specify path where the cheatsheets should be stored. E.g.

```
$ echo >  ~/.config/cheat/cheat <<<EOF
{
  "CHEAT_COLORS"      : true,
  "CHEAT_COLORSCHEME" : "light",
  "CHEAT_EDITOR"      : "vi",
  "CHEAT_PATH"        : "<path-you-would-like-to-use>"
}
EOF
```

But that's just possible workround for you know. Would be nice to create the file automatically when --user installation is used. Not sure whether it is possible to that in such way.

**Comment by fpersson** [comment]
I have same problem.

**Comment by vaz-ar** [comment]
> 
> 
> Not sure how the installation exactly will end now. But in case you don't have created config file automaticaly on the user level, just create it and specify path where the cheatsheets should be stored. E.g.
> 
> ```
> $ mkdir ~/.config/cheat
> $ echo >  ~/.config/cheat/cheat <<<EOF
> {
>   "CHEAT_COLORS"      : true,
>   "CHEAT_COLORSCHEME" : "light",
>   "CHEAT_EDITOR"      : "vi",
>   "CHEAT_PATH"        : "<path-you-would-like-to-use>"
> }
> EOF
> ```
> 
> But that's just possible workround for you know. Would be nice to create the file automatically when --user installation is used. Not sure whether it is possible to that in such way.

Sorry for the late reply.
This is not a solution as the cheat sheets are not on the machine, they were not installed anywhere

**Comment by pirat89** [comment]
@vaz-ar Aah, I see. I am sorry for misleading info.

**Comment by chrisallenlane** [comment]
@vaz-ar , @fpersson 

Sorry for these issues.

Python was causing all sorts of problems along these lines, so I just released `cheat` v3, which re-implements the project in Go. Please upgrade and give it a try. The community-sourced cheatsheets are now separate from the main executable, so make sure to clone those as well:

https://github.com/cheat/cheatsheets
