### ISSUE TITLE
Linux - No cheat sheet found

### ISSUE THREAD

**Issue by Virgula0** [cheat/cheat#448]
I'm on a distro based on Debian (Parrot OS), once cheat is installed via pip trying to cheat whatever command gives the following error:

`No cheat sheet found`

To fix it I have to export CHEAT_PATH='/path/to/my/cheats' manually as shown in the index of GitHub, the problem is that I have to do it manually every time at every O.S start up. Any fix about this?

**Comment by pirat89** [comment]
@Virgula0 What about
```
echo "CHEAT_PATH=/path/to/my/cheats" >> ~/.bashrc
```

**Comment by Virgula0** [comment]
Applied, I rebooted and it doesn't work, however I mismatched to describe properly the problem before, it's the `CHEAT_USER_DIR` wrong and not `CHEAT_PATH`

**Comment by cnnblike** [comment]
same issue on mac os.

**Comment by fpersson** [comment]
/usr/share/cheat does not exist for me (fresh install with "sudo pip install cheat")

**Comment by sdondley** [comment]
I can confirm. I'm running debian stretch. I did `apt-get install python-pip package` and then `pip install cheat`. Like the comment above, directory shows /usr/share/cheat as cheat directory but there is nothing in there. Cheats are located in `/usr/local/lib/python2.7/dist-packages/usr/share/cheat/ ` as well.

**Comment by jacobus** [comment]
Same problem on Ubuntu 19.04

**Comment by arthurcgusmao** [comment]
If you run into this error, probably the actual cheats dir location should be somewhere in your home directory:
```console
find ~/ -name cheat | grep /usr/share/cheat
```
If that is the case, creating symlink to directory will fix, e.g.,
```console
ln -s ~/bla/bla/.../usr/share/cheat /usr/share/cheat
```

**Comment by chrisallenlane** [comment]
Hi, all

The installation process was causing all sorts of problems, so I re-write `cheat` from scratch in Go. Please upgrade to `cheat` v3 (released moments ago), which should definitively resolve this problem.

Thanks, and sorry for the headache.
