### ISSUE TITLE
chealt -l crasch

### ISSUE THREAD

**Issue by fpersson** [cheat/cheat#449]
cheat -l crash when cheat's can be found. (I installed cheat with the --user option)

```
$ cheat -l
Traceback (most recent call last):
  File "/home/fredrik/.local/bin/cheat", line 93, in <module>
    print(sheets.list(), end="")
  File "/home/fredrik/.local/lib/python2.7/site-packages/cheat/sheets.py", line 59, in list
    pad_length = max([len(x) for x in self.get().keys()]) + 4
ValueError: max() arg is an empty sequence
```

**Comment by exploide** [comment]
This will be fixed when my PR #447 gets merged.

**Comment by sgarrison05** [comment]
Has this been fixed yet?  I just install 2.5.1 and got this error.

**Comment by exploide** [comment]
No it has not been fixed yet. And I expect it won't be fixed in the Python implementation of cheat since the maintainer announced there will be a rewrite in Go. See #470

**Comment by sgarrison05** [comment]
Thank you for the reply. I like the program but been hit or miss whether I can get it to install and work. 

Shon Garrison
Email: sgarrison05@sbcglobal.net

**Comment by chrisallenlane** [comment]
@sgarrison05 , @exploide 

Yeah, I apologize for this issue. I can't get this version of `cheat` to install either, which is, of course, a huge embarrassment.

Frustrated with these recurring installation issues, I've been working heavily on the Golang implementation. I'm actually giving a talk on it on Friday of this week, so - hopefully - it will be finished by then! (It is actually quite near to finished as is.)

The Go implementation will solve these problems definitively. The new release will also provide support for often-requested features, like the ability to created "nested" cheatsheet directories.

I'll update this ticket with installation instructions when the new executable is released. I apologize for this inconvenience in the meantime.

**Comment by sgarrison05** [comment]
Actually I got it to install on every Ubuntu variant. Just not Debian, for which it’s based on. 

Love the app though. 

Shon Garrison
Email: sgarrison05@sbcglobal.net

**Comment by chrisallenlane** [comment]
Hi, guys.

`cheat` v3 has now been released, which should resolve this issue. Please upgrade and let me know if you encounter any errors.

Thanks!
