### ISSUE TITLE
Way to pipe to less in color in Linux?

### ISSUE THREAD

**Issue by sdondley** [cheat/cheat#451]
On my mac, I can do this:

`cheat tmux | less -r`

and I can get color output. Without the -r option, I can see the code for color.

But this is a no go on my Linux box for some reason. I don't see color and I don't see the code for the colors in the output.

Would be great if I could this working. Thanks.

UPDATE: Forgot to add that I do have Pygmatize installed.

**Comment by sdondley** [comment]
This bit of trickery worked: https://stackoverflow.com/a/32981392/1641112

But the indentation is all messed up.

**Comment by sdondley** [comment]
OK, here is a super hack fix: https://stackoverflow.com/questions/55368652/pipe-colored-output-of-command-into-the-less-command

**Comment by psizek** [comment]
I made this pull request a month ago, which sort of solves your problem: https://github.com/cheat/cheat/pull/441

**Comment by chrisallenlane** [comment]
@sdondley, `less -R` (capital `R`) should work on Linux. (It works on my machine.) IIRC, OSX implements a different `less` binary than the one typically found in the Linux ecosystem.
