### ISSUE TITLE
change editor to vim

### ISSUE THREAD

**Issue by jinfagang** [cheat/cheat#458]
How to change editor to vim?

**Comment by exploide** [comment]
Create a config file, e.g. in `~/.config/cheat/cheat`, based on the content of https://github.com/cheat/cheat/blob/master/config/cheat

You can set another editor there.

**Comment by blurm** [comment]
@exploide Same issue here. The link is broken
Is the cheat.example.conf the valid format for config file? where shoud I put it? ~/.cheat?

**Comment by exploide** [comment]
Apparently the new sample config file is https://github.com/cheat/cheat/blob/master/config/cheat.example.conf

AFAIK it is read from various locations. I have placed it in `.config/cheat/cheat` (the last is the file, not a directory).

However, there will be a new major release in a few days, see #470 (actually it is a rewrite). It might be possible that everything config related changes then.

**Comment by chrisallenlane** [comment]
> However, there will be a new major release in a few days, see #470 (actually it is a rewrite). It might be possible that everything config related changes then.

It will. I'm planning on releasing the new version tomorrow. Sorry for this inconvenience until then.

In the short term: ensure that `EDITOR` or `VISUAL` is set and exported to `vim`. `cheat` should pick up on them (unless you've installed via the `snap` package, which unfortunately can't access those envvars.)

**Comment by chrisallenlane** [comment]
@jinfagang , @exploide , @blurm 

Sorry about this issue. I just released `cheat` v3, which should resolve the problem. Please upgrade and let me know if you encounter any problems. Thanks.
