### ISSUE TITLE
couldn't launch vi 

### ISSUE THREAD

**Issue by houyichaochaochao** [cheat/cheat#465]

**Comment by houyichaochaochao** [comment]
what should i do

**Comment by DerUser** [comment]
This repo is for problems/feature request with cheat and not to support all listed commands.

You should probably ask this on [StackOverflow.com](https://stackoverflow.com) or in another help forum (possibly for your Distro).

**Comment by houyichaochaochao** [comment]
Thanks ,I am not have to use it ,just okay
