### ISSUE TITLE
Support for decoupled individual cheetsheet

### ISSUE THREAD

**Issue by xsuchy** [cheat/cheat#466]
It would be nice to support cheatsheet shipped by the original project. E.g. I just added the cheatsheet to mock https://github.com/rpm-software-management/mock/commit/c0eaa8b0c63db1e1314bf1638d301b2cc1545fa3
But if anyone ever adds cheat sheet directly to this project, we will get file conflicts.

It would be nice if you can parse e.g. /usr/share/cheat.d/* as well and hint maintainers that if they want to manage cheatsheet on they own they should put it there. And document which one will get priority if file exists in both /usr/share/cheat.d/ and /usr/share/cheat/

**Comment by chrisallenlane** [comment]
@xsuchy 

I just published `cheat` v3, which was an entire re-implementation of the project in Go. As part of that effort, I have removed cheatsheets from the `cheat` executable and externalized them into a new repository:

https://github.com/cheat/cheatsheets

That said, this issue should now be resolved. Please upgrade to `cheat` v3 and try it out.
