### ISSUE TITLE
Colors not readable

### ISSUE THREAD

**Issue by BjoernDaase** [cheat/cheat#469]
On a standard, unthemed Fedora 30 installation, the gray in the output is not readable.

OS: Fedora
Shell: zsh
Version: 2.5.1

![image](https://user-images.githubusercontent.com/24682367/64081853-fecf3100-cd06-11e9-8416-7eb26060fefa.png)

**Comment by TomasKorbar** [comment]
Hi @BjoernDaase,
Please try to set environment variable CHEAT_COLORSCHEME to "dark". You can also change this setting globally in "/etc/cheat".

**Comment by BjoernDaase** [comment]
@TomasKorbar Thanks, that makes it much more readable.

Anyway, instead of setting it manually I think we should set it dependant on the values stored in the profile of the current terminal found in `/org/gnome/terminal/legacy/profiles:`

**Comment by pirat89** [comment]
@BjoernDaase  Good idea about to use colors set by user in terminal.  Just I believe the way to read it from file is not good. I guess that every terminal and system will use different path to store the file. And additionally, people could install terminal on their own, every path can have different format, and some terminals are using additional profiles. For example your path is very nonstandard. Is it Mac OS? Instead, it could be better to get such colors from terminal. I haven't looked at it in the past, but maybe LS_COLORS could contain even such data? (I am not sure about that, as I really haven't play around that before).

**Comment by BjoernDaase** [comment]
@pirat89 Oh, the path given is just the `gsettings` key, sorry for not making that clear. And no, it is Fedora 31.

I just had a quick glimpse at `LS_COLORS`. Your idea sounds good, the output definitely looks usable.

**Comment by chrisallenlane** [comment]
Hi, guys. `cheat` v3 how now been released, which re-implements `cheat` entirely from scratch, now in Go. Please upgrade to the newest version, and let me know if you encounter any errors. Thanks!

**Comment by BjoernDaase** [comment]
Thanks @chrisallenlane!  
Now that you've closed the issue, I assume that `cheat` is now following `LS_COLORS`?

**Comment by chrisallenlane** [comment]
@BjoernDaase, `cheat` now allows a user to manually specify a desired colorscheme via the wonderful [chroma][] library. All of the following colorschemes are supported:

https://xyproto.github.io/splash/docs/

You just need to specify which color scheme you would like to use via the `config` file.

[chroma]: https://github.com/alecthomas/chroma
