### ISSUE TITLE
Go version doesn't follow softlinks

### ISSUE THREAD

**Issue by m3nu** [cheat/cheat#474]
I noticed that pointing the new config file to a softlink (which in turn points to the `dotfiles` folder produces an error:

```
$ cheat -l
failed to list cheatsheets: failed to load cheatsheets: could not create sheet: failed to read file: /Users/manu/.cheat, read /Users/manu/.cheat: is a directory
```

Would make sense if it would follow softlinks.

Workaround: point to source folder instead of softlink.

**Comment by chrisallenlane** [comment]
Hi, @m3nu 

Would you mind sharing your configs here? I'm actually using symlinks for all of my configs (likewise symlinking to dotfiles), so this _should_ work.

**Comment by chrisallenlane** [comment]
One thing to note is that you need to make sure to initialize a config file with `cheat --init`, and then link to the location of that config file, rather than your `.cheat` directory. `cheat` v3 is entirely incompatible with v2, so there may be a bit of re-arranging necessary.

**Comment by m3nu** [comment]
Sure. I only changed the `cheatpaths:` part. This works OK (points to source folder):

```
  - name: personal
    path: ~/.dotfiles/cheat/.cheat
    tags: [ personal ]
    readonly: true
```

The symlink:

```
$ ls -la ~ | grep cheat
lrwxr-xr-x    1 manu  staff        22 Mar  1  2016 .cheat -> .dotfiles/cheat/.cheat
```

This fails: (point to symlink)

```
  - name: personal
    path: ~/.cheat
    tags: [ personal ]
    readonly: true
```

```
$ cheat -l
failed to list cheatsheets: failed to load cheatsheets: could not create sheet: failed to read file: /Users/manu/.cheat, read /Users/manu/.cheat: is a directory
```

**Comment by chrisallenlane** [comment]
Hmm - that may actually be a bug. I'll dig into that shortly. Thanks for the information.

**Comment by chrisallenlane** [comment]
Confirmed that this is a bug in `3.0.3` and earlier.

**Comment by chrisallenlane** [comment]
@m3nu, thanks again for reporting this. This should now be resolved in version `3.0.4`. Please upgrade and let me know if you encounter any further errors.

**Comment by m3nu** [comment]
Thanks for checking, @chrisallenlane. Can confirm that symlinked folders now work as expected.

```
  - name: personal
    path: ~/.cheat
    tags: [ personal ]
    readonly: true
```

```
$ ls -la ~ | grep .cheat
lrwxr-xr-x    1 manu  staff        22 Mar  1  2016 .cheat -> .dotfiles/cheat/.cheat
```

**Comment by chrisallenlane** [comment]
Glad to hear, @m3nu. Thanks.
