### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [cheat/cheat#482]
This one probably got lost in the great rewrite of 2019, but your license file is currently missing.

I also noticed you dual-licensed it, which *is* a thing, but I think you'd need to release two different versions to do that, Especially since GPL3 and MIT aren't compatible.

I also don't know useful it is to dual-license between two open-source licenses, I'd stick to one or the other, but that is of course up to you.

**Comment by chrisallenlane** [comment]
Yeah, there's a discussion about this going on in #477. I'm going to close this as a dupe, but feel free to share any thoughts there. I'm actively soliciting opinions.
