### ISSUE TITLE
3.0.3 failed to load cheatsheets

### ISSUE THREAD

**Issue by Antisunny** [cheat/cheat#491]
after upgrading from 3.0.1 to 3.0.3, cheatsheets is not loaded and config is forcely required.

> failed to list cheatsheets: failed to load cheatsheets: error walking path: lstat ~/.dotfiles/cheat/community: no such file or directory

**Comment by chrisallenlane** [comment]
Hi, @Antisunny 

Please paste your config file here, as well as the output from the following commands:

```sh
cheat -v
```

```sh
cheat -d
```

Thanks.

**Comment by Antisunny** [comment]
## cheat -v

```
3.0.3
```

## cheat -d

**but there is no dir named `.dotfiles` under home folder.**

```
community: /Users/USER/.dotfiles/cheat/community
work:      /Users/USER/.dotfiles/cheat/work
personal:  /Users/USER/.dotfiles/cheat/personal
```

installed by homebrew

**Comment by Antisunny** [comment]
the `.config/cheat` configuration folder is also missing, I manully created it.

**Comment by chrisallenlane** [comment]
Hi, @Antisunny 

I don't think we have any bugs on our hands here.

> the .config/cheat configuration folder is also missing, I manully created it.

This is as expected. See `cheat -h`:

```
Examples:

  To initialize a config file:
    mkdir -p ~/.config/cheat && cheat --init > ~/.config/cheat/conf.yml
```

> but there is no dir named .dotfiles under home folder.

Also expected. `.dotfiles` is just a placeholder - you need to remove those values and replace them with the actual paths on your filesystem.

So it sounds like `cheat` is working alright. I probably could have made the documentation clearer in places, though. I'll take a look at improving the docs in the future.

Let me know if you encounter any other issues. Thanks.
