### ISSUE TITLE
Render markdown documents

### ISSUE THREAD

**Issue by chrisallenlane** [cheat/cheat#494]
**Is your feature request related to a problem? Please describe.**
Currently, `cheat` will apply syntax-highlighting to markdown documents, but it does not _render_ them the way one may expect to view them on Github. See #488 for context.

**Describe the solution you'd like**
It would perhaps be useful if `cheat` could render markdown documents, in addition to simply applying syntax-highlighting to them.

Because we do not want to make an assumption regarding which behavior the user would prefer, perhaps cheatsheets that should be rendered could be prefaced with `render: true` front-matter. Additionally, perhaps the equivalent configuration option could be added to `conf.yml`.

**Additional context**
Does there exist a layout-engine (written in Go) that could be imported into the project?

**Comment by chrisallenlane** [comment]
I have yet to come up with a portable way to implement this that wouldn't entail meaningful scope-creep, so I'm going to set this idea aside for now.

**Comment by rickswe** [comment]
Created #763 with some ideas, perhaps I should have commented the issue on here.
