### ISSUE TITLE
it can't work in macOS with catalina.

### ISSUE THREAD

**Issue by yzzshmily** [cheat/cheat#499]
I install it with brew 
```
brew install cheat
```
when i execute   " cheat -d " in terminal，
 
teminal said:

        could not locate config file.

**Comment by chrisallenlane** [comment]
Hi, @yzzshmily 

`cheat` works on Catalina. I use it daily.

Please provide the following information:

**cheat version info**
Please paste the output of `cheat -v` here.

**cheat configuration info**
If your bug pertains to how cheatsheets are loaded and/or displayed, please
paste here the following information:

1. The output of `cheat -d`
2. The contents of your `conf.yml` file

Thanks.

**Comment by GarrettStanford21** [comment]
I am also having the following error:

` could not locate config file.`

Output of `cheat -v` was: `3.2.2`
Output of `cheat -d` was: ` could not locate config file.`

I am not sure what my `conf.yml' file is.

Thanks!
