### ISSUE TITLE
it can't work in macOS Catalina. (zsh)

### ISSUE THREAD

**Issue by kobadesu** [cheat/cheat#507]
in clean installed macOS Catalina. (zsh)
I install it with brew

```
% brew install cheat
```

teminal said:

```
% cheat
could not locate config file

% cheat mysql
could not locate config file

% cheat -d
could not locate config file 
```

Environment:

```
% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88

% cheat -v
3.1.0
```

but no problem in pip install.

**Comment by chrisallenlane** [comment]
Hi, @kobadesu 

You need to create a config file. Please run the following command:
```
mkdir -p ~/.config/cheat && cheat --init > ~/.config/cheat/conf.yml
```

You'll then need to edit the config file:
```
nano ~/.config/cheat/conf.yml
```

(You can use whichever editor you prefer.)

More information is available here:
https://github.com/cheat/cheat#configuring

Once the config file has been created and populated with the correct information, you should be all set.
