### ISSUE TITLE
Add a command like "cheat init" to create automatically the needed folders and the configuration file

### ISSUE THREAD

**Issue by fmaida** [cheat/cheat#512]
I'm actually using cheat on macOS 10.13.6, but I think that this could also be applied on linux distros as well.
The first time I tried to launch cheat without configuring it, I got some errors.
In order to get cheat up and running I read the documentation and according to it, I did this to get it working:

1) As suggested in the documentation, I have executed `mkdir -p ~/.config/cheat && cheat --init > ~/.config/cheat/conf.yml`

2) I have also created some directories with these commands:
`mkdir ~/.dotfiles`
`mkdir ~/.dotfiles/cheat`
`mkdir ~/.dotfiles/cheat/personal`
`mkdir ~/.dotfiles/cheat/work`

3) Then I have cloned the community cheatsheet GIT repository with:

`git clone https://github.com/cheat/cheatsheets.git ~/.dotfiles/cheat/community`

Was my behaviour correct?

If it is, wouldn't it be easier if cheat could be able to handle all this work by itself? 
What I mean is: in one of your future updates, could you automatise this entire process? 
It would be really nice if cheat could do this all by itself the first time it is launched, or eventually if that's not possible at least when the user enter a special command, like for example `cheat init`.

Thank you for your time and patience
Kind regards.

**Comment by exploide** [comment]
Your point 1 is correct. Issue #501 already keeps track of simplifying all of this.

Point 2 is only necessary if you indeed want to have your cheatsheets under the `.dotfiles` directory. It's an example. You can personalize this as you want. You can even just have one single cheatpath configured to point to an arbitrary directory intended to contain your custom cheatsheets.

@chrisallenlane This was exactly what I meant with

> Another small thing: The config file generated by cheat --init contains example cheatpaths in ~/.dotfiles. I could imagine that some users not familiar with the concept of dotfile repositories have no idea what this is and could be confused because they think folders need to have this name and hesitate to change that.

in #501.

Point 3 is correct if you want to use the community provided cheatsheets.

**Comment by fmaida** [comment]
I can understand that some will prefer to fine-tune the whole experience by putting the cheatsheets and the configuration files in their preferred folders, but IMHO I also think that many users that are not very skilled (like me) will be already okay with the default folder names and paths.
This is why I'm thinking that for some of us would be nice to have a command that installs everything you need in advance; you could execute it and have everything set-up for you.

**Comment by chrisallenlane** [comment]
Hi, guys. Thanks for the thoughtful discussion here.

@fmaida, yeah, the current process for getting `cheat` configured for the first time is unfortunately cumbersome. As @exploide noted, we're tracking that issue in #501, and getting that resolved is a current priority. Fortunately, @stefanc opened a PR yesterday that gets us much closer to the goal, so with luck, we'll have this cleaned up within a week or two.

@exploide 

> @chrisallenlane This was exactly what I meant in #501 with ...

Yeah, it's pretty clear now that a lot of users are struggling with this. I'm still mulling over the optimal solution, but I agree with your diagnosis of the problem.

> Maybe users feel more comfortable with having a minimal default config that works out of the box and leaving the advanced features as optional, e.g. in comments.

Regardless of the specific implementation details, what you've outlined above is definitely the correct approach.

Anyway, @fmaida, I'll close this ticket in favor of #501, but feel free to contribute to the discussion there.

Thanks!

**Comment by chrisallenlane** [comment]
Oh, and btw, @fmaida: it sounds like you eventually got `cheat` working (even if it was a bit of a headache). That said, if you're still having any specific problems with your configuration, let me know here and I'll help out. Thanks.

**Comment by fmaida** [comment]
The process of installing and setting it up wasn't difficult at all, it's just that I am basically VERY LAZY and quite often I try to avoid reading manuals and readme documents :-D
Being that lazy, I was only wondering if there could be a way to make the life easier to the lazy people like me :-D
