### ISSUE TITLE
Make Raspberry Pi builds available

### ISSUE THREAD

**Issue by seatrout** [cheat/cheat#520]
Would it be possible to add executables for the Raspberry Pi (arm64) to this site? It runs a popular form of linux, one on which it is just as easy to forget command options as it is on any more powerful computer. 
I can't figure out how to compile the program myself on the pi; otherwise I wouldn't trouble you.

**Comment by bernermic** [comment]
@seatrout if you have snap on your Pi you can try this: `sudo snap install cheat`.
I build the arm version and this is available in the snap store now.

**Comment by seatrout** [comment]
Thank you! I was unaware of snap, but everything seems to be working now. 

Almost by definition you need "cheat" most on the systems you use least. My pis run for months untouched doing small useful jobs and then all of a sudden I find I need to do something with one and can't remember how ...

**Comment by chrisallenlane** [comment]
Hi again, @seatrout 

I'm now publishing ARM releases as of version `3.2.2` (released a moment ago). Releases are available for download here:

https://github.com/cheat/cheat/releases/tag/3.2.2

That said, you may as well continue using @bernermic's `snap` implementation. An advantage of using his `snap` versus downloading a compiled binary is that he compiles `cheat` when the package installs, which means that you will always get the correct version for your system. (Thanks for this, @bernermic!)

As an aside, @seatrout, if you're curious regarding how to compile a Go app for ARM, see the relevant commit on my PR:

https://github.com/cheat/cheat/pull/521/commits/7f3ae2ab306668a905d8ac13546961708a72cbc4

You just have to pass a few options to the Go compiler, and it does the rest.

Thanks, guys. Closing as resolved.

**Comment by seatrout** [comment]
Thank you so much!
