### ISSUE TITLE
Failed to load config error

### ISSUE THREAD

**Issue by pr0letariat** [cheat/cheat#537]
Recently got the latest version of `cheat` and came across the following error:

```
$ cheat -l
failed to load config: failed to resolve symlink: /home/me/cheat/cheatsheets/community: lstat /home/me/cheat: no such file or directory
```

```
$ cheat -d
failed to load config: failed to resolve symlink: /home/me/cheat/cheatsheets/community: lstat /home/me/cheat: no such file or directory
```

```
$ cheat -v
3.5.1
```

Using the default `conf.yml`:

```
~/.config/cheat$ ll
total 4
-rw-r--r-- 1 me me 2672 Feb  6 00:19 conf.yml
```
Have already done:

```
cheat --init > ~/.config/cheat/conf.yml
```

**Comment by literaryno4** [comment]
Hi, I encountered the same problem with you.
- I have tried to download the source code and compile it locally.
`cd cheat-3.5.1`
`make install`
It come with no reaction and seem not work. I am not familiar with go and not sure the way to compile source code.

- I also tried to install cheat with pip.
`pip install cheat`
`cheat -v`
showing `cheat 2.5.1`, this old version seems not work either.

Please tell me when you figure this problem out.

**Comment by chrisallenlane** [comment]
Hi, @pr0letariat 

You need to edit your config file to specify the correct paths to where you are storing your cheatsheets locally. Look for the entries that look like this:

```yaml
cheatpaths:

  - name: community
    path: ~/.dotfiles/cheat/community
    tags: [ community ]
    readonly: true
```

Change `path` to the correct path on your filesystem. That should resolve your problem.

I'm going to close this ticket, but you're welcome to re-open it if you need further assistance. Thanks.

**Comment by bernermic** [comment]
Hey @chrisallenlane 😀
this is also an issue for the snap version of cheat. 
Did you think about creating the cheat folders when they are not there initially?

Then this question would not come up.

For the snap version the path is not really intuitive. Having cheat create the path for me would make things easier.

Greetings 
Michael
