### ISSUE TITLE
A cheat to use available cheats

### ISSUE THREAD

**Issue by aborruso** [cheat/cheat#539]
Hi,
I have installed cheat, but I do not find a simple to note - a cheat - on how to install and use the community-sourced [cheatsheets available](https://github.com/cheat/cheatsheets).

I think it would be a good starting point.

Thank you

**Comment by bernermic** [comment]
Hi @chrisallenlane 
a good improvement may be to automatically create the folders `~/cheat/cheatsheets/community/` (if not given) and copy the community cheatsheets in the configured folder.
This way a user simply can run cheat without having to touch the config (if he does not want to).

This also would be benefitial for the snap version, as I do not have an easy way of auto generating this folders/files from within the snap when cheat is started first after a fresh installation.

What do you think?

**Comment by chrisallenlane** [comment]
Hi, guys

@aborruso, thanks for the input. I'm still getting the impression from users that `cheat` is too difficult to configure initially.

@bernermic, yeah, something like that would probably be the way to go. I've been reluctant to avoid creating "official" cheatpaths for a while now, because such a thing isn't strictly necessary. That said, this seems to be causing confusion for a significant number of users, so perhaps the approach I've taken so far has caused more harm than good.

I'll think about this for a bit, and will open a `feature-request` ticket when I have a proposed detailed solution. I'll tag both of you on it so you can review before I begin the implementation.

**Comment by aborruso** [comment]
Hi @chrisallenlane and firt of all thank you.

I think that to avoid creating "official" cheatpaths is a good idea.

My request is to add a sort of cheat, in the readme of the project: 

```markdown
# How to add community-sourced cheats

To add the community-sourced cheats these are the simple steps:

- git clone ... 
- then ...

```

Best regards

**Comment by bernermic** [comment]
Hey @aborruso & @chrisallenlane,
 
I would rater follow a different approach and give users who don't want to take care of a setup to make it a no brainer. 
I would argue that many users only want to use cheat right out of the box and will be rather confused when they have to clone something after they installed cheat.

Maybe a dialogue at the beginning if cheat should do the setup for the user or something along this lines could also work?

Thanks for taking care of this @chrisallenlane I am looking forward to check in next time :)

Greetings
Michael

**Comment by chrisallenlane** [comment]
@aborruso, @bernermic 

Hi, guys. Sorry for the slow progress on this ticket. Work has been keeping me busy.

> I'll think about this for a bit, and will open a feature-request ticket when I have a proposed detailed solution. I'll tag both of you on it so you can review before I begin the implementation.

Minor change in plans here.

Writing code is more fun than writing RFCs, so I just took a stab at implementing this. When you have a moment, please take a look at this draft PR opened from my personal fork:

https://github.com/cheat/cheat/pull/542

If you have the time, please build that on your machines, temporarily rename your cheat config file, and then attempt to view a cheatsheet. `cheat` should recognize that you don't have a config file, and will then prompt you with an "installer" that asks if you'd like to create a config file and (automatically) clone the community cheatsheets.

Also, I simplified this somewhat from my original vision. Initially, I was thinking that we'd have to prompt the user for desired config paths, cheatsheet paths, etc. I realized, though, that this code path is for users that don't care about those details (and want `cheat` to "just work"), so I chose some defaults that I figured would be sensible.

This is still a bit rough, but you get the idea. (I still need to consolidate some file paths, write some unit-tests, and address some probably cross-platform issues.)

What do you guys think of that approach?

**Comment by chrisallenlane** [comment]
And, yeah, @bernermic 

> I would argue that many users only want to use cheat right out of the box and will be rather confused when they have to clone something after they installed cheat.

I think that's the key point here. That's why I eschewed the more nuanced config wizard and just hard-coded some sensible defaults. This will probably work better for the users that don't care about these details.

**Comment by chrisallenlane** [comment]
Oh, note to self: don't forget to update the `README` also.

**Comment by bernermic** [comment]
> @aborruso, @bernermic
> 
> Hi, guys. Sorry for the slow progress on this ticket. Work has been keeping me busy.
> 
> > I'll think about this for a bit, and will open a feature-request ticket when I have a proposed detailed solution. I'll tag both of you on it so you can review before I begin the implementation.
> 
> Minor change in plans here.
> 
> Writing code is more fun than writing RFCs, so I just took a stab at implementing this. When you have a moment, please take a look at this draft PR opened from my personal fork:
> 
> #542
> 
> If you have the time, please build that on your machines, temporarily rename your cheat config file, and then attempt to view a cheatsheet. `cheat` should recognize that you don't have a config file, and will then prompt you with an "installer" that asks if you'd like to create a config file and (automatically) clone the community cheatsheets.
> 
> Also, I simplified this somewhat from my original vision. Initially, I was thinking that we'd have to prompt the user for desired config paths, cheatsheet paths, etc. I realized, though, that this code path is for users that don't care about those details (and want `cheat` to "just work"), so I chose some defaults that I figured would be sensible.
> 
> This is still a bit rough, but you get the idea. (I still need to consolidate some file paths, write some unit-tests, and address some probably cross-platform issues.)
> 
> What do you guys think of that approach?

@chrisallenlane many thanks for your work 😀
I will try it asap and give you feedback.
But this will most likely not be this week, as I am busy right now.
Greetings

**Comment by chrisallenlane** [comment]
@aborruso, @bernermic 

Hi, guys. I implemented an "installer" that should make it very painless for first-time users to install and configure `cheat`. It's included in the `3.7.0` release:

https://github.com/cheat/cheat/releases/tag/3.7.0

To try this out, momentarily rename your config file (so `cheat` thinks you don't have a config file). An installer should launch (on the CLI) that offers to create both a default config file and download the community cheatsheets.

Please try it out and let me know what you think!

I'm going to close this ticket as "resolved", but feel free to re-open it (either of you) if necessary.

Thanks!

**Comment by aborruso** [comment]
Hi @chrisallenlane you are very kind: it works and it's great!

Thank you very much

**Comment by chrisallenlane** [comment]
Glad to hear it, @aborruso. Thanks! :tada:
