### ISSUE TITLE
Undesired behavior within ~/.cheat directory

### ISSUE THREAD

**Issue by chrisallenlane** [cheat/cheat#544]
**A description of the problem**
The Python implementations of `cheat` (version `1.x` and `2.x`) assumed that configuration would live in `~/.cheat/conf.yaml`. Since the introduction of "directory-scoped" cheatsheets in `3.3.0`, this can cause an unexpected failure when running `cheat` within `~` when `~/.cheat` exists.

Fundamentally, the problem is that `cheat` now interprets files contained within `~/.cheat` to be directory-scoped cheatsheets, however the prior `~/.cheat/conf.yaml` file would be shaped in a way that the current front-matter parser will not expect. This can cause `cheat` to crash with a runtime `panic`.

There are probably a few solutions here. Perhaps the most elegant would be simply to silently ignore malformed cheatsheets, rather than `panic` when they are encountered.

Feedback is welcomed on this and other solutions.

**cheat version info**
This affects `3.3.0` through `3.7.0`.

**Comment by bernermic** [comment]
@chrisallenlane I think this approach is fine 👍

But a message to the user should be printed.
Let’s say someone updates from a 2.x to 3.x version - that user could have personal cheatsheets he wants to keep.
So a message like „hey please move your stuff from a to b „ would help.
It could also just log a link to a help section in cheat‘s readme.
I happily support in writing this readme section and make a pull request.

**Comment by chrisallenlane** [comment]
Hi, @bernermic 

Thanks for your :eyes: and your input.

I was thinking about this a bit more last night, as well as looking at the offending code. I think we have two separate issues here, really.

First: the frontmatter parser is just plain broken. When it encounters malformed frontmatter, it will `panic`. (This is straightforward to fix.) Thus, contrary to my ticket here, the problem isn't really the "home directory" - it's just that `~` is a common location where malformed "frontmatter" will be encountered.

Regarding your remarks:

> Let’s say someone updates from a 2.x to 3.x version - that user could have personal cheatsheets he wants to keep.

I hadn't considered that, but that's important as well. In my opinion, this is a second, distinct issue: I didn't write "upgrading" instructions anywhere.

I've been working on a `man` page for `cheat`, which I'd like to include (probably) with the next release. I'll add an "UPGRADING" section there, as well as a quick blurb in the `README`. Thanks for spotting this!

**Comment by chrisallenlane** [comment]
This is now resolved in `3.7.1`:
https://github.com/cheat/cheat/releases/tag/3.7.1
