### ISSUE TITLE
Recommended way to list cheatsheets among *all* cheat directories

### ISSUE THREAD

**Issue by be-rock** [cheat/cheat#548]
If i have a `community` sourced cheatsheet in `readonly: true` but i want to supplement that data with what's in my `personal` cheatsheet, how do i get the output of `cheat` to show info from both cheatpath `community` and cheatpath `personal`.

E.g. `$ cheat tar`
will show results from both `community` and `personal` dirs.

**Comment by chrisallenlane** [comment]
@be-rock, there is currently no way to do this. I can see the value in this feature, though. (I've wished I had this once or twice myself already.)

Proposal: what about adding an `--all` (`-a`) flag that displays output from all sources (rather than the most "local" source)? I don't think that would entail a huge amount of effort.

**Comment by be-rock** [comment]
that sounds like a great solution to me.  and maybe even an option during setup to set the default directory criteria e.g. `[community|personal|work|all]`.  or an even simpler solution would be to simply alias cheat to `alias cheat='cheat --all'`.

Regardless, thank you and keep up the great work on this awesome tool :)

**Comment by chrisallenlane** [comment]
Update: solving this properly will actually require more effort than I initially estimated. I still intend to do it - I just need to find the time. I'm hoping to be able to address this some time within the next two weeks.

**Comment by chrisallenlane** [comment]
Well, this took a little longer than "two weeks", but the `--all` flag is available as of release `4.2.0`:
https://github.com/cheat/cheat/releases/tag/4.2.0

**Comment by linnabraham** [comment]
> Well, this took a little longer than "two weeks", but the `--all` flag is available as of release `4.2.0`:
> https://github.com/cheat/cheat/releases/tag/4.2.0

This was a feature that I wanted for sometime now. Thanks for implementing it. 
However, I was thinking of aliasing cheat to cheat --all. But it looks like when using the -all flag, the priority gets reversed. The community cheatsheets shows up first which seems counter-intuitive to me. I would like my personal cheatsheets to take preference. Am i missing something here?
