### ISSUE TITLE
show cheatsheets from multiple cheatsheet folders 

### ISSUE THREAD

**Issue by linsong** [cheat/cheat#555]
I have a personal cheatsheet for `gdb` within personal folder. When I run `cheat gdb` command, only my personal notes displayed. 

`cheat gdb` should show both community and personal cheatsheet together, maybe each part starting with a header/title(tag?).

I don't want to put the community cheatsheet above my personal cheatsheet within one file, because in this way, the community cheatsheet can not get updates from community cheatsheets git repo easily. 

Thanks for the great tool, it makes my CLI life much easier!

**Comment by chrisallenlane** [comment]
Hi, @linsong.

Thanks for the kind words. I'm glad you're enjoying `cheat`!

The feature you're requesting here is on the roadmap. We're discussing it over in #548. I'm going to close this ticket in favor of that one, but feel free to share your thoughts regarding the proposed implementation there.
