### ISSUE TITLE
Make Linux 32-bit builds available

### ISSUE THREAD

**Issue by ivanruvalcaba** [cheat/cheat#562]
Would it be possible to add executable for the Linux i386/i686/x86 to this site?

I understand that the main Linux distributions are dropping support for this architecture, but not everyone uses Ubuntu/Linux Mint (so sorry! Debian user here). I also know that there is the possibility of resorting to the installation via snap, however I personally consider that it creates more problems than your application could solve (Debian does not have support for snap packages by default making it an additional step in installation/configuration).

Thank you and best regards.

**Comment by chrisallenlane** [comment]
Hi, @ivanruvalcaba 

Go fortunately makes this very easy. I just published `cheat@3.10.1`, which makes available a 386 executable:

https://github.com/cheat/cheat/releases/tag/3.10.1

I'll support that build target going forward.

I'm going to close this as resolved. Just shout if you have any questions.

Thanks.
