### ISSUE TITLE
Do not export all content provided when "cheat something"

### ISSUE THREAD

**Issue by zwkcoding** [cheat/cheat#567]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my cheat outputed content is too long for me to catch the head part. I must scroll to read it.

**Describe the solution you'd like**
It would be better If I can add an option to cheat for me to choose how many lines to show at first.

**Describe alternatives you've considered**
Or, like "man" command, it opens the instruction to allow me to type space to see more.

**Additional context**
None

**Comment by zwkcoding** [comment]
although I can open the cheatsheet with "cheat -e something", but it's not so elegant.

**Comment by chrisallenlane** [comment]
Hi, @zwkcoding 

Yeah, this has been annoying me (and others) for a while.

I just published [cheat@v4.0.0][4]. Please upgrade to it.

>  It would be better If I can add an option to cheat for me to choose how many lines to show at first.

I decided to take a different approach that we have discussed before. You can now specify a `pager` value in your config file, and content will be filtered through that pager when it is written to `stdout`. (The recommended pager on Linux is `less -FRX`)

Example:
https://github.com/cheat/cheat/blob/4e9b2928b3308a79caef26fe575afd63d5e65786/configs/conf.yml#L17-L18

Please try it out and let me know what you think. Thanks.

[4]: https://github.com/cheat/cheat/releases/tag/4.0.0

**Comment by zwkcoding** [comment]
I have tried it, very helpful ! @chrisallenlane

**Comment by chrisallenlane** [comment]
Glad to hear :smiley:
