### ISSUE TITLE
New grammar path/cheatsheet?

### ISSUE THREAD

**Issue by lengyijun** [cheat/cheat#576]
Do you consider supporting such grammar:
```
cheat community/git
```
which is equivalent to
```
cheat -t community git
```

I think `community/grammar` is more concise.

**Comment by exploide** [comment]
This would conflict with the ability of cheat to use cheatsheets from subdirectories. How to distinguish `community` being a tag or a subfolder in your example?

**Comment by lengyijun** [comment]
Sorry I don't know about subdirectories grammar

**Comment by chrisallenlane** [comment]
Yeah, it's as @exploide - this syntax is already in-use.

Thanks, guys.
