### ISSUE TITLE
Support UTF-8 while display cheat files

### ISSUE THREAD

**Issue by WBobby** [cheat/cheat#579]
After adding some notes using utf-8, the text will not be correctly shown.
e.g. add utf-8 symbol while use "cheat -e notes". I can see the symbol when I set encoding=utf-8 in vim.
but when I call it by "cheat notes", the symbol cannot correctly display.

**Comment by chrisallenlane** [comment]
Hi, @WBobby 

This _should_ already work. Are you certain that your terminal is configured to support UTF-8 currently? Please show me the output of the following command:

```sh
env | grep LANG
```

Thanks.

**Comment by chrisallenlane** [comment]
Closing as stale.
