### ISSUE TITLE
allow "cheat -t=compression" without "-l"

### ISSUE THREAD

**Issue by 8go** [cheat/cheat#581]
**Is your feature request related to a problem? Please describe.**
No problem. Just an idea for a small improvement.

**Describe the solution you'd like**
cheat -t=compression # does not work, as documented
cheat -t=compression -l # works, as documented
idea: 
cheat -t=compression # let this work as well and have it default to `cheat -t=compression -l `

**Additional info**
This would make it a tiny bit more user friendly in my opinion.

**Comment by chrisallenlane** [comment]
I like this idea. I've considered this in the past, actually.

I just implemented this locally. It was literally a two-line change.

I'll run this on my own machine for a day or two. If it doesn't cause any problems, I'll merge it in. Thanks for the suggestion.

**Comment by chrisallenlane** [comment]
This is now implemented in the `4.1.0` release:
https://github.com/cheat/cheat/releases/tag/4.1.0

Thanks!
