### ISSUE TITLE
failed to load config: failed to resolve symlink

### ISSUE THREAD

**Issue by bbrendon** [cheat/cheat#584]
**A description of the problem**
*You will be asked if you would like to install the community-sourced cheatsheets the first time you run cheat.*

Instead I get 

```
 ~  cheat                                                                              
failed to load config: failed to resolve symlink: /home/bbrendon/.config/cheat/cheatsheets/community: lstat /home/bbrendon/.config/cheat/cheatsheets: no such file or directory
 ~  cheat -v                                                                         
4.0.4
 ~      
```

**cheat version info**
4.0.4

**cheat configuration info**
If your bug pertains to how cheatsheets are loaded and/or displayed, please
paste here the following information:

1. The output of `cheat -d`
```
 ~  cheat -d                                                              
failed to load config: failed to resolve symlink: /home/bbrendon/.config/cheat/cheatsheets/community: lstat /home/bbrendon/.config/cheat/cheatsheets: no such file or directory
 ~       
```

**Comment by SinRoot** [comment]
workaround - change config. I was create folder `cheatsheets.personal` and write to config
```
- name: community
    path: /home/dan/.config/cheat/cheatsheets
    tags: [ community ]
    readonly: true

- name: personal
    path: /home/dan/.config/cheat/cheatsheets.personal
    tags: [ personal ]
    readonly: false
```

But still need to fix for new users

**Comment by Zikoel** [comment]
Hi, same error here! I have created the missing folders manually, but now the remain empty! I suppose that for the community cheats should be an automatic fetching! Nothing happen after the init step!

**Comment by aborruso** [comment]
The same for me :(

**Comment by chrisallenlane** [comment]
I'm on PTO this week, so I finally have some time to devote to this project again. I'll try to track down the problem.

**Comment by kylebradshaw** [comment]
hit the same issue

**Comment by ChrisYin** [comment]
Same for me, any possible solution?

**Comment by bsahane** [comment]
For my setup I created a directory for `personal` using
```bash
$ mkdir -p /home/bsahane/.config/cheat/cheatsheets/personal
```
And updated `path` for `community` in `conf.yml` as below
```yml
  - name: community
    path: /usr/share/cheat/
    tags: [ community ]
    readonly: true

  - name: personal
    path: /home/bsahane/.config/cheat/cheatsheets/personal
    tags: [ personal ]
    readonly: false
```
So `community` and `personal` both working properly
```bash
$ cheat -d
community: /usr/share/cheat
personal:  /home/bsahane/.config/cheat/cheatsheets/personal
```

**Comment by Lonenso** [comment]
I think this is embrassing, this error is because "config" presents but cheatpath doesn't exist.
moreover, like @Zikoel said, if user creates the community cheatsheets directory, it remains empty.

I am not sure if is it good to have a builtin cheatsheets' source management, see this https://github.com/cheat/cheat/issues/658

**Comment by bbrendon** [comment]
I just tried this program again and it didn't fail.
