### ISSUE TITLE
Cannot change EDITOR from config file

### ISSUE THREAD

**Issue by martinsaravia** [cheat/cheat#591]
Hi guys !

I have changed the editor from vim to atom in a config file that I set in a non-default directory, but I cannot get it to work; I get the error: 

failed to edit cheatsheet: exec: "atom": executable file not found in $PATH

I think that it is a problem of environment variables and not a bug, but I cannot solve it. The outuput of "which atom" is /usr/bin/atom. Strangely, vim works ok and which vim gives nothing. 

**cheat version info**
4.1.0

I am using Ubuntu 20.04 with cheat installed from snap. 

Thank you in advance; thanks for cheat, is great !

**Comment by chrisallenlane** [comment]
Hi, @martinsaravia 

> I am using Ubuntu 20.04 with cheat installed from snap.

I'm not sure if the `snap` version of `cheat` currently supports changing the editor, or if the configuration process is perhaps different. The `snap` maintainer is @bernermic, who may be able to help you.

You may also try downloading the `cheat` executable directly from the [Releases][] page, though unfortunately, an executable downloaded directly will not receive automatic updates (unlike the `snap` package, which will).

[Releases]: https://github.com/cheat/cheat/releases

**Comment by martinsaravia** [comment]
Hi Chris ! Thanks very much for your reply. I have downloaded the executable and it works fine with the same configuration file. 

I'll wait for Michael's reply in order to see if we can get the snap version to work. 

Thanks !

Martin

**Comment by chrisallenlane** [comment]
That's great to hear, @martinsaravia. I'll close this ticket in that case, but feel free to continue the discussion here as necessary.

**Comment by bernermic** [comment]
Hi @martinsaravia ,

> I'll wait for Michael's reply in order to see if we can get the snap version to work.


Unfortunately I do not see an easy way for the snap usage in your usecase (as I have to package atom then with the cheat snap).

> failed to edit cheatsheet: exec: "atom": executable file not found in $PATH

Cheat snap ships only with vim & nano for the moment. So if the binary works for you you should stick to this one for now.
