### ISSUE TITLE
README.md is listed as a cheat

### ISSUE THREAD

**Issue by kapad** [cheat/cheat#600]
**A description of the problem**
In my personal cheat repository, some files that aren't cheats are also being listed as cheats. One of this is the README.md. 

**cheat version info**
4.1.1

**cheat configuration info**
1. Output of `cheat -d`
community: /Users/kapad/dotfiles/shell/plugins/cheatsheets
personal:  /Users/kapad/dotfiles/shell/plugins/cheats

2. Output of `ls -1 -A /Users/kapad/dotfiles/shell/plugins/cheats`
```
.git
LICENSE
README.md
```

_This could also be considered a feature for adding a support for an ignore file or something on those lines. I can reclassify accordingly if you think it should be._

**Comment by chrisallenlane** [comment]
Hi, @kapad 

As best as I can tell the `cheat` "installer" doesn't create any cheatsheets by default in your `personal` cheatpath. (It creates the directory, but does not create any files therein.)

Question: do you know how those files got there? Did the installer somehow create those automatically?

If not, they can simply be removed. `cheat` itself does not require (or expect) these files to be there.

**Comment by kapad** [comment]
I added the `README.md` file myself. And also a `LICENSE` file. I think for cheat to load every single file in my repo isn't ideal. 

[The repo](https://github.com/kapad/cheats) that I created for my own cheats got an autocreated `README.md` and a `LICENSE` file. The issue is that these files are also loaded as cheats. 

I haven't verified with the code, but after some tests I think the only files and directories that are not loaded as cheats are those starting with `.`. 

This issue may be incorrectly reported as a bug. Should I reclassify as a feature/enhancement?

**Comment by chrisallenlane** [comment]
Oh, I see.

Yeah, this is just fundamental to how `cheat` works - every file within a directory that's specified as a `cheatpath` will be considered  a cheatsheet, by definition. You can either just delete the readme and license if you don't care about them, or simply move your cheatsheets into a subdirectory of your repository.
