### ISSUE TITLE
Allow setting CHEAT_USE_FZF in the config.yaml

### ISSUE THREAD

**Issue by kapad** [cheat/cheat#601]
**Is your feature request related to a problem? Please describe.**
I don't like having to set an ENV var for using fzf even though I'm setting another env var pointing to a config file. 

**Describe the solution you'd like**
I want to be able to provide the option to use fzf in the config.yaml. 
Additionally, I'd also like to be able to pass in the options to call fzf with in the config.yaml.

**Comment by chrisallenlane** [comment]
Hi, @kapad 

I agree that it's not ideal that `fzf` integration is configured via an envvar. That said, I think there could be significant complexity involved in moving this configuration into the config file.

This is the heart of the issue: while the `cheat` _executable_ is configured via the config file, `fzf` integration is external to the binary. This happens in one of a few shell scripts.

As an example, here's the `bash` script:
https://github.com/cheat/cheat/blob/master/scripts/cheat.bash#L15-L23

If we wanted to replace that environment variable, we'd need to find a way to do the following:

1. Locate the `cheat` config file (there are many paths where it may be found, and they vary by platform)
2. Parse that file (ideally without using exotic dependencies)
3. Set a default value if `CHEAT_USE_FZF` isn't set at all (this admittedly isn't hard)
4. Do the above _for every shell and environment_ that we want to support

With that said, I won't say conclusively that I _won't_ do this, but my instincts are that this is a lot of effort for relatively little gain.

Thoughts?

**Comment by kapad** [comment]
I'd like to setup a working build locally first. 

https://github.com/cheat/cheat/issues/603

**Comment by chrisallenlane** [comment]
I've thought about it a bit, and I don't think this is going to be possible to implement in a portable way (which won't be a nightmare to maintain), so I'm unfortunately going to close this ticket.
