### ISSUE TITLE
Add development section to the README/wiki

### ISSUE THREAD

**Issue by kapad** [cheat/cheat#603]
**Is your feature request related to a problem? Please describe.**
Add a section to the README/wiki for how to set things up for local development and testing. Apologies in advance if it's already there. I've missed it.

**Additional context**
I'm new to golang and some guide with the simplest of baby steps would be helpful.

**Comment by Lonenso** [comment]
there's a Makefile in the codebase, so just run `make` until everything works. For me, I missed `pandoc`, `revive`. 

Do not forget to install `go`.

**Comment by chrisallenlane** [comment]
Hi, @kapad 

I'm sorry it has taken me so long to get to this.

I've added a `HACKING.md` file to the project, which gives a brief introduction to developing `cheat`:
https://github.com/cheat/cheat/blob/master/HACKING.md

Please let me know if you'd like to see any other information contained therein.

Closing as resolved for now.

**Comment by kapad** [comment]
Hi @chrisallenlane . Thank you for the response and the hacking guide. :)
