### ISSUE TITLE
Can the installation be detailed for newbies?

### ISSUE THREAD

**Issue by RidenShark** [cheat/cheat#608]
Hi. I understand this is intended for power users. But as someone new to Linux, the one-sentence installation in the documentation is hard for me to follow.

> To install it, download the executable from the releases page and place it on your PATH.

I have downloaded the release `cheat-linux-amd64.gz` to my `home/riden/` directory. I unzipped it into a dir called `cheat` in my directory. Added `export PATH="/home/riden/cheat:$PATH"` in my `.bashrc` file. Restarted the terminal. But after that, I have no clue how to proceed.

When I type `cheat` it says `Command 'cheat' not found, did you mean: ...` .

Can anyone please guide me? Not to be an ass, but us newbies need a bit of handholding than a 'draw the rest of the owl' - even for installations. :(

**Comment by sethiojas** [comment]
>export PATH="/home/riden/cheat:$PATH" 

This statement is wrong. Replace it with `export PATH="/home/riden/cheat":$PATH`. Note `:$PATH` is outside of quotation marks. The variables are colon delimited so the line translates to add `/home/riden/cheat` and then all the values already in PATH (denoted by `$PATH`) and update the value (`export PATH = ...`).

P.S. I'm not a power user :wink:

**Comment by moracabanas** [comment]
I came to this cheatsheet tool because I am having a hard time on linux every day, and I am now having a hard time trying to install this cheatsheet tool.

**Comment by moracabanas** [comment]
> > export PATH="/home/riden/cheat:$PATH"
> 
> This statement is wrong. Replace it with `export PATH="/home/riden/cheat":$PATH`. Note `:$PATH` is outside of quotation marks. The variables are colon delimited so the line translates to add `/home/riden/cheat` and then all the values already in PATH (denoted by `$PATH`) and update the value (`export PATH = ...`).
> 
> P.S. I'm not a power user 😉

Doing that `export PATH = ..` I am in fear to override the actual $PATH which is actually quite large on my WSL linux and I am not understanding what am I doing at all.
Why I shouldn't just `chmod +x cheat-linux-amd64` and `mv cheat-linux-amd64` to /bin?

**Comment by ecogit** [comment]
This Linode guide explains it step-by-step: [Installing and Using the cheat Command on Linux](https://www.linode.com/docs/guides/linux-cheat-command/).

Installation in a nutshell:
```
curl -LO https://github.com/cheat/cheat/releases/download/4.2.3/cheat-linux-amd64.gz
gzip -dk cheat-linux-amd64.gz
sudo mv cheat-linux-amd64 /usr/local/bin/cheat
sudo chmod +x /usr/local/bin/cheat
cheat --version
```
- - -
To configure cheatsheets:
```
cheat ls
```
>>> This starts a config wizard which you twice confirm with 'Y' and then is all set. Enjoy "cheating"!

**Comment by chrisallenlane** [comment]
@RidenShark, thanks for the issue report, and I'm sorry it has taken me so long to reply.

If you're still interested in this, this morning I created an `INSTALLING.md` file that contains more detailed instructions. I hope you find it helpful:

https://github.com/cheat/cheat/blob/master/INSTALLING.md

I'm going to close this ticket, but feel free to re-open it if necessary.

Thanks.
