### ISSUE TITLE
Android/Termux support.

### ISSUE THREAD

**Issue by nerd190** [cheat/cheat#609]
Cheat works amazingly on my PC but doesnt work in Termux (only --help works) "unable to load config, unsupported os" please allow Android to be supported. Thank you!

**Comment by chrisallenlane** [comment]
Hi, @5c0tt-b0t

Can you elaborate a bit on your use-case? I wouldn't have imagined that `cheat` would be useful on an Android device. Are you running a shell on a rooted phone, or what? How did you install `cheat` on that phone in the first place?

I don't mean to pry - I just want to make sure that I understand the problem that we're trying to solve :slightly_smiling_face: 

Am I correct in assuming that your phone is an ARM device? With a bit of luck, I'll just need to update the `Makefile` to produce an ARM build, and you'll be good to go.

**Comment by chrisallenlane** [comment]
Oh, wait - I'd forgotten: I'm already building for ARM. IIRC, somebody asked for RasPi support a while ago:

https://github.com/cheat/cheat/blob/883a17092f08cbcd4b24b8a42d22f14443369ce1/Makefile#L36

Have you tried each ARM version? Maybe you just need to find the right executable.

**Comment by 5c0tt-b0t** [comment]
Of course! I am sometimes away from my PC, sometimes its for days at a time (once a month I go fishing for the weekend), other times, its just long commutes (on the train to work), I discovered Termux about 5 years ago and its always filled the void perfectly, some examples: Stream movies/music thats on my PC at home, or from cloud storage with ”rclone”. SSH into my PC to fetch a PDF/Ebook to read, push/pull with Git, sync/backup with "rsync" & "restic", stream Youtube, Spotify, Twitch & BBC without using closed-source apps full of trackers and/or ads, as the years have passed, the list goes on! I have always used Linux CLI, Android works as good as my Arch Linux PC, or old Mac laptop I have, none of this requires root access, although I do root all my devices after their 2 year warranty period is up, in fact, it works so well I even bought a Samsung Tablet and small bluetooth keyboard, laptops die in a few hours, my tablet lasts 12 hours a charge and can be charged via battery bank, it lasts for days!
Being able to read/write a cheatsheet would be great too, there are alternatives I can use that work as expected, but I have used this a long time on my PC/laptop and I like it alot, I'd like to use it on-the-go via my tablet or phone, I also have a Raspberry Pi, so the ARM64/aarch64 binary would be double appreciated! THANK YOU!!

**Comment by chrisallenlane** [comment]
That's really interesting. Thanks for the info. Now I want to try this out too.

Given that I'm already building for ARM, I think there's a chance that I simply need to add `"android"` or something right here:

https://github.com/cheat/cheat/blob/883a17092f08cbcd4b24b8a42d22f14443369ce1/internal/config/paths.go#L31

With luck, it will otherwise "just work."

I'll screw around with this for a bit, and will report back :slightly_smiling_face:

**Comment by 5c0tt-b0t** [comment]
I agree, I believe its only this value that is needed, I can build this from source perfectly via Termux, it just wont allow any commands other than '--help' to run as its not listed as a supported OS.
Honestly, Android is more vanilla Linux than my Mac laptop is! (Android uses GNU utils, Mac uses BSD) so find, grep, cut, awk, sed all work as expected without Mac's weird flags, like "find -s" etc, which is only BSD. All of the above are built into your device already, it even has Vi as its default editor! LOL.
Using Termux extends its usage with a package manager that runs in "/data/data”, a non-root directory (its uses "apt", but only contains verified working pkgs that can be build via Termux itself), so you can trade the limited utils provided by Androids "toybox" with "busybox" and "coreutils" instead by adding them to your $PATH.
So I can use 'neovim' editor & push with 'git', whilst streaming Spotify (ad-free) on a train in the morning! all from a little Samsung tablet! :D

You can compile with Clang or GCC, languages include Go, Rust, Ruby, Python, C, C#, C++, NodeJS, Lua, Swift, PHP, Perl, Dart (too many to list! including Java/Kotlin, but this usually needs root access).
All of your PC dotfiles/configs/scripts are easy to use on Android too, just grep them all for the word "usr", (this is a root directory on Android), then use sed or your editor to replace "usr" with "$PREFIX", prefix points to Termux's usr, which is a data directory, so no root needed. Profit!
Saved me a ton of money! my new phone "OnePlus 8 Pro" has 12GB's of RAM, thats 50% more than my PC has! although its CPU isnt as strong as an i5, unlike my PC, its also not having to run a sluggish Windows environment!
I also have an Android TV box so I can use Termux on my 50" inch TV when i'm at home!
Thanks again!

**Comment by Mandymoore680** [comment]
What do you mean????

**Comment by chrisallenlane** [comment]
Sorry it has taken me so long to get to this.

So, I just set up an ancient Android tablet here to test this using Termux. To my surprise, everything worked perfectly, after I installed `git` and `vim`. (You need the former to download cheatsheets via the installer, and the latter to edit them.)

I'm using the ARM5 Linux binary.

@5c0tt-b0t, will you please respond to this thread with the specified error message that you've encountered? Clearly this is doable, given that it "works on my machine." I probably just need to smooth out some rough edge that I'm not encountering to get it working on yours too.

Thanks.
