### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by MandiYang** [cheat/cheat#612]
Thanks for submitting a bug report. Please provide the following information:

**Permssion denied**
A config file was not found. Would you like to create one now? [Y/n]: Y
Would you like to download the community cheatsheets? [Y/n]: Y
warning: unable to access '/etc/gitconfig': Permission denied
Cloning into '/root/snap/cheat/common/.config/cheat/cheatsheets/community'...
warning: unable to access '/etc/gitconfig': Permission denied
fatal: unknown error occurred while reading the configuration files
failed to run installer: failed to clone cheatsheets: failed to clone cheatsheets: exit status 128

**version 4.2.0**

**cheat configuration info**
If your bug pertains to how cheatsheets are loaded and/or displayed, please
paste here the following information:

1. The output of `cheat -d`
A config file was not found. Would you like to create one now? [Y/n]: Y
Would you like to download the community cheatsheets? [Y/n]: Y
warning: unable to access '/etc/gitconfig': Permission denied
Cloning into '/root/snap/cheat/common/.config/cheat/cheatsheets/community'...
warning: unable to access '/etc/gitconfig': Permission denied
fatal: unknown error occurred while reading the configuration files
failed to run installer: failed to clone cheatsheets: failed to clone cheatsheets: exit status 128
2. The contents of your `conf.yml` file

**Comment by bernermic** [comment]
Hello @MandiYang,
thanks for your report. Unfortunately I can not reproduce your reported bug. 
It seems you are installing the snap as root user, is that correct? Can you please try to do this as non root user?
Greetings

**Comment by MandiYang** [comment]
Thank's, installing via source is much easier cuz you don't must be root. I close this issue.
