### ISSUE TITLE
Help with install

### ISSUE THREAD

**Issue by JouBqa** [cheat/cheat#613]
I have cheat-linux-amd64 in folder ~/Downloads/Applications/Cheat and I added this to .bashrc: export PATH="$HOME/Downloads/Applications/Cheat:$PATH"

When I try to run `cheat` it's not found. Any advice on what I did wrong?

**Comment by JouBqa** [comment]
doing `echo $PATH` shows that it hasn't actually been added to path?

**Comment by JouBqa** [comment]
This didn't work either export PATH="${PATH:+${PATH}:}~Downloads/Applications/Cheat"

**Comment by Rom1deTroyes** [comment]
If the file is named `cheat-linux-amd64` the command to launch will be :
```sh
$ cheat-linux-amd64 --version
```

Try to rename the file, and be sure it's executable :
```sh
$ mv cheat-linux-amd64 cheat
$ chmod +x cheat
```

**Comment by JouBqa** [comment]
Thank you! :) 
Moved it to `~/.local/bin/ renamed to cheat and it works
Never done this before as I'm a new user

**Comment by chrisallenlane** [comment]
@Rom1deTroyes, thank you for the assist!

@JouBqa, I need to improve the documentation a bit. I'll try to make this clearer going forward. :slightly_smiling_face:
