### ISSUE TITLE
Duplicate cheatsheets while autocompleting at $HOME

### ISSUE THREAD

**Issue by diegombeltran** [cheat/cheat#618]
Thanks for submitting a bug report. Please provide the following information:

**A description of the problem**
I have a symlink ($HOME/.cheat) to another folder containing cheatsheets ($HOME/user/git/dotfiles/.cheat). If I press tab twice to autocomplete while I'm at $HOME, lots of cheatsheets are duplicated. This does not happen in other directories.

Autocomple at $HOME:
![image](https://user-images.githubusercontent.com/7081281/115382569-24a79300-a1d5-11eb-874e-c1e802796e55.png)
![image](https://user-images.githubusercontent.com/7081281/115382753-54ef3180-a1d5-11eb-963c-5c2dd280cc7b.png)

Autocomplete in other directories:
![image](https://user-images.githubusercontent.com/7081281/115382846-6f290f80-a1d5-11eb-90ee-aedb0ab28140.png)
![image](https://user-images.githubusercontent.com/7081281/115382899-7c45fe80-a1d5-11eb-9e08-4835f630def9.png)

I'm using the completion script with oh-my-zsh, all components are the last available here at the repository.

**cheat version info**
4.2.0

**cheat configuration info**

1. The output of `cheat -d`
Community: /home/user/git/dotfiles/.cheat/community
Work:      /home/user/git/dotfiles/.cheat/work
Personal:  /home/user/git/dotfiles/.cheat/personal

2. The contents of your `conf.yml` file

```
# The editor to use with 'cheat -e <sheet>'. Defaults to $EDITOR or $VISUAL.
editor: nvim

# Should 'cheat' always colorize output?
colorize: true

# Which 'chroma' colorscheme should be applied to the output?
# Options are available here:
#   https://github.com/alecthomas/chroma/tree/master/styles
style: monokai

# Which 'chroma' "formatter" should be applied?
# One of: "terminal", "terminal256", "terminal16m"
formatter: terminal16m

# The paths at which cheatsheets are available. Tags associated with a cheatpath
# are automatically attached to all cheatsheets residing on that path.
#
# Whenever cheatsheets share the same title (like 'tar'), the most local
# cheatsheets (those which come later in this file) take precedent over the
# less local sheets. This allows you to create your own "overides" for
# "upstream" cheatsheets.
#
# But what if you want to view the "upstream" cheatsheets instead of your own?
# Cheatsheets may be filtered via 'cheat -f <tag>' in combination with other
# commands. So, if you want to view the 'tar' cheatsheet that is tagged as
# 'community' rather than your own, you can use: cheat tar -f community
cheatpaths:

  # Paths that come earlier are considered to be the most "global", and will
  # thus be overridden by more local cheatsheets. That being the case, you
  # should probably list community cheatsheets first.
  #
  # Note that the paths and tags listed below are just examples. You may freely
  # change them to suit your needs.
  - name: Community
    path: ~/.cheat/community
    tags: [ community ]
    readonly: true

  # Maybe your company or department maintains a repository of cheatsheets as
  # well. It's probably sensible to list those second.
  - name: Work
    path: ~/.cheat/work
    tags: [ work ]
    readonly: false

  # If you have personalized cheatsheets, list them last. They will take
  # precedence over the more global cheatsheets.
  - name: Personal
    path: ~/.cheat/personal
    tags: [ personal ]
    readonly: false
```

**Comment by diegombeltran** [comment]
OK, I just saw this in the README:

```
Directory-scoped Cheatpaths

At times, it can be useful to closely associate cheatsheets with a directory on your filesystem. cheat facilitates this by searching for a .cheat folder in the current working directory. If found, the .cheat directory will (temporarily) be added to the cheatpaths.
```
So changing the symbolic link to .cheats instead of .cheat and chaning the config accordingly fixes this. My bad!

I'm closing the issue now. Thank you anyway!!

**Comment by chrisallenlane** [comment]
Aha. Yeah, you're not the first user to get tripped up by this, unfortunately. I should probably improve the visibility of this feature, given that it can be a "gotcha" otherwise.

I'm glad you were able to work this out. Thanks for the detailed bug report!
