### ISSUE TITLE
Release an ARM64 binary

### ISSUE THREAD

**Issue by PabloLec** [cheat/cheat#627]
**Is your feature request related to a problem? Please describe.**
Currently, there is no ARM64 binary for `cheat`.
As it is a common architecture, especially with Raspberry Pi 4, it should be added to existing options.
Furthermore, [Go already support ARM64 builds natively](https://github.com/golang/go/wiki/GoArm).

**Describe the solution you'd like**
Simply add build instructions to `Makefile`.

**Describe alternatives you've considered**
/

**Additional context**
I just added PR #628 to please my Cortex A72.

**Comment by chrisallenlane** [comment]
Your PR was merged into `4.2.2`, and your `arm64` build will be including in all forthcoming releases. Thanks very much!
