### ISSUE TITLE
Cannot install via "go get" command

### ISSUE THREAD

**Issue by leahsiddall-wm** [cheat/cheat#649]
**A description of the problem**
When trying to install via the "go get" command, it does not complete and gives this warning/error: 

```text
installing executables with 'go get' in module mode is deprecated.
```

Complete output here: 

```sh
❯ go get -u github.com/cheat/cheat/cmd/cheat

go: downloading github.com/cheat/cheat v0.0.0-20211009161301-12ffa4cb5c87
go: downloading github.com/docopt/docopt-go v0.0.0-20180111231733-ee0de3bc6815
go: downloading github.com/alecthomas/chroma v0.9.1
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading gopkg.in/yaml.v1 v1.0.0-20140924161607-9f9df34309c0
go: downloading github.com/alecthomas/chroma v0.9.4
go: downloading golang.org/x/sys v0.0.0-20211103235746-7861aae1554b
go: downloading github.com/dlclark/regexp2 v1.4.0
go: downloading github.com/danwakefield/fnmatch v0.0.0-20160403171240-cbb64ac3d964
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.


❯ go get -u github.com/cheat/cheat/cmd/cheat

go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

**cheat version info**
n/a

```text
❯ uname -a
Darwin MacBook-Pro 19.6.0 Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64 x86_64
❯ go version
go version go1.17.1 darwin/amd64
```

**Comment by wangwenqiangGitHub** [comment]
I also this erro

**Comment by Rom1deTroyes** [comment]
Can you try to use `go install` instead :
```sh
go install github.com/cheat/cheat/cmd/cheat@latest
```

**Comment by aminnaggar** [comment]
this is what I get when I run your command @Rom1deTroyes 

```
can't load package: package github.com/cheat/cheat/cmd/cheat@latest: cannot use path@version syntax in GOPATH mode
```

**Comment by shmuhammad2004** [comment]
> Can you try to use `go install` instead :
> 
> ```shell
> go install github.com/cheat/cheat/cmd/cheat@latest
> ```

This works for me

**Comment by pablomalo** [comment]
Related: #666

**Comment by ninsy** [comment]
Same problem occurred here, when I had tried to use
```
go get -u github.com/cheat/cheat/cmd/cheat
```
with golang version `go1.13.8 linux/amd64`, until then I run

```
go install github.com/cheat/cheat/cmd/cheat@latest
```
with version `go1.18 linux/amd64`, installation succeded. Just my 3 cents - I can recommend installing [goenv](https://github.com/syndbg/goenv) to swap between golang versions. :)

**Comment by chrisallenlane** [comment]
Sorry it has taken me so long to address this. I have been quite busy.

I believe what we're seeing here is simply a change in the behavior of the `go` executable itself:
https://go.dev/doc/go-get-install-deprecation

> Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.

`cheat` itself is built with Go 1.18, and I want to do things the correct, forward-looking way, so let's consider `go install` to be the appropriate tool for installing `cheat` (using the Go toolchain) going forward. (Thanks @Rom1deTroyes for your contribution to the thread.)

I'm going to close this as resolved, though I'm making a mental note that this needs to be documented in the `README`.
