### ISSUE TITLE
Failed to write to pager: exec: "less": executable file not found in %PATH%

### ISSUE THREAD

**Issue by ondrasek** [cheat/cheat#655]
Whenever I invoke `cheat`, I get the following error: _failed to write to pager: exec: "less": executable file not found in %PATH%_.

For example:
```
$cheat -c -s ssh
failed to write to pager: exec: "less": executable file not found in %PATH%
$cheat -l
failed to write to pager: exec: "less": executable file not found in %PATH%
$cheat ssh
failed to write to pager: exec: "less": executable file not found in %PATH%
```

My environment:
```
echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Installed via scoop.

**Comment by ondrasek** [comment]
The default config from `cheat --init` does contain the pager key. I suggest removing the default pager configuration, using the PAGER env variable, or adjusting the error message to indicate that pager is configured explicitly in the conf.yml file.

**Comment by clach04** [comment]
Appears to duplicate #571

**Comment by chrisallenlane** [comment]
@ondrasek, thanks for reporting this. I'm going to close this and track this issue along with other Windows-only issues in #665, but I can confirm this behavior.

I believe I have a fix for this working locally. It should ship with the next version of `cheat`, hopefully later today.
