### ISSUE TITLE
Please help i tried many game hacks but they dont work what should i do 

### ISSUE THREAD

**Issue by cambo32** [cheat/cheat#662]
first one 
![VS](https://user-images.githubusercontent.com/102672909/160846604-95d83b7a-9dab-44f3-8524-287a1b1aba70.png)
![VS2](https://user-images.githubusercontent.com/102672909/160846608-22a9ca09-4945-424a-a5d2-ee6a41b6c14f.png)
second one 
![VS3](https://user-images.githubusercontent.com/102672909/160846652-540eb334-3c14-4640-b9a3-5379316a12cf.png)
![VS4](https://user-images.githubusercontent.com/102672909/160846658-8ba329ff-6190-474d-9609-6abd5ce8f9b1.png)
third one 
![VS5](https://user-images.githubusercontent.com/102672909/160846716-c838558b-418b-4649-bf1d-158369e3a1e4.png)
![VS6](https://user-images.githubusercontent.com/102672909/160846731-b37ee6f6-c9ba-4def-943b-5a4d72f6fa1e.png)

**Comment by chrisallenlane** [comment]
You have the wrong repository, so I'm going to close this ticket.
