### ISSUE TITLE
Leading whitespace stripped in first line of cheatsheet

### ISSUE THREAD

**Issue by exploide** [cheat/cheat#663]
**A description of the problem**
If a cheatsheet contains leading whitespace in the first line, it gets stripped. For example the following content

```
  10 pizza
 250 pasta
1234 salat
```

becomes this when shown by `cheat`

```
10 pizza
 250 pasta
1234 salat
```

This messes up the formatting. So I consider this a subtle bug.

**cheat version info**
4.2.2

**cheat configuration info**

```
colorize: true
style: monokai
formatter: terminal16m
```

**Comment by chrisallenlane** [comment]
Oh, hmm...

I had intended to strip leading newlines, but I hadn't considered this case. I'll take a look at what we can do here.

Thanks for reporting this.

**Comment by chrisallenlane** [comment]
@exploide, thanks for reporting this.

Having thought about this for a while, I've decided to simply stop stripping whitespace on cheatsheet output. There's really on reason why I should be making formatting decisions on the user's behalf, and if a cheatsheet contains a whitespacing error, `cheat -e` is right there to fix it.

Please upgrade to `4.3.2`:
https://github.com/cheat/cheat/releases/tag/4.3.2

I'm going to close this as resolved. Thanks!
