### ISSUE TITLE
Microsoft Windows default config file not usable

### ISSUE THREAD

**Issue by clach04** [cheat/cheat#665]
Thanks for submitting a bug report. Please provide the following information:

**A description of the problem**

New install of cheat exe https://github.com/cheat/cheat/releases/tag/4.2.3 requires a config, the default one created is not usable.

Bad/incorrect defaults for:

  * editor - vim can't be assumed available. Recommend "notepad", a terrible editor but will be available and advanced user can change this
  * pager - less not available, recommend "more" (remove is an option but not my personal recommendation)
  * colorize - when set to true does NOT work with default, regular CMD.exe Window. Recommend "false" and/or open a windows colorize issue
  * cheatpaths for both community and personal are relative to the current directory. Recommend using the same path as the location of the config file that is created. I.e. default config file appears to be `%APPDATA%\cheat\conf.yml`, recommend using `%APPDATA%\cheat\cheatsheets\community` and `%APPDATA%\cheat\cheatsheets\personal`

**cheat version info**
4.2.3

**cheat configuration info**
If your bug pertains to how cheatsheets are loaded and/or displayed, please
paste here the following information:

1. The output of `cheat -d`

Can't really do that due to issues #665 (this one :wink:), #655, and #571 :stuck_out_tongue_winking_eye: - see below for actual content if made to work:

    community: cheatsheets\community
    personal:  cheatsheets\personal

3. The contents of your `conf.yml` file

        ---
        # The editor to use with 'cheat -e <sheet>'. Defaults to $EDITOR or $VISUAL.
        editor: vim

        # Should 'cheat' always colorize output?
        colorize: true

        # Which 'chroma' colorscheme should be applied to the output?
        # Options are available here:
        #   https://github.com/alecthomas/chroma/tree/master/styles
        style: monokai

        # Which 'chroma' "formatter" should be applied?
        # One of: "terminal", "terminal256", "terminal16m"
        formatter: terminal16m

        # Through which pager should output be piped? (Unset this key for no pager.)
        pager: less -FRX

        # The paths at which cheatsheets are available. Tags associated with a cheatpath
        # are automatically attached to all cheatsheets residing on that path.
        #
        # Whenever cheatsheets share the same title (like 'tar'), the most local
        # cheatsheets (those which come later in this file) take precedent over the
        # less local sheets. This allows you to create your own "overides" for
        # "upstream" cheatsheets.
        #
        # But what if you want to view the "upstream" cheatsheets instead of your own?
        # Cheatsheets may be filtered via 'cheat -t <tag>' in combination with other
        # commands. So, if you want to view the 'tar' cheatsheet that is tagged as
        # 'community' rather than your own, you can use: cheat tar -t community
        cheatpaths:

          # Paths that come earlier are considered to be the most "global", and will
          # thus be overridden by more local cheatsheets. That being the case, you
          # should probably list community cheatsheets first.
          #
          # Note that the paths and tags listed below are placeholders. You may freely
          # change them to suit your needs.
          #
          # Community cheatsheets must be installed separately, though you may have
          # downloaded them automatically when installing 'cheat'. If not, you may
          # download them here:
          #
          # https://github.com/cheat/cheatsheets
          #
          # Once downloaded, ensure that 'path' below points to the location at which
          # you downloaded the community cheatsheets.
          - name: community
            path: cheatsheets/community
            tags: [ community ]
            readonly: true

          # If you have personalized cheatsheets, list them last. They will take
          # precedence over the more global cheatsheets.
          - name: personal
            path: cheatsheets/personal
            tags: [ personal ]
            readonly: false

          # While it requires no configuration here, it's also worth noting that
          # 'cheat' will automatically append directories named '.cheat' within the
          # current working directory to the 'cheatpath'. This can be very useful if
          # you'd like to closely associate cheatsheets with, for example, a directory
          # containing source code.
          #
          # Such "directory-scoped" cheatsheets will be treated as the most "local"
          # cheatsheets, and will override less "local" cheatsheets. Likewise,
          # directory-scoped cheatsheets will always be editable ('readonly: false').

**Comment by clach04** [comment]
Just reviewed the code, looks like https://github.com/cheat/cheat/blob/12ffa4cb5c874207df89018f14054f495a6757b1/cmd/cheat/cmd_init.go#L44 maybe where the path is set incorrectly without the correct leading path. Sadly I'm not familiar with the code to make a PR.

**Comment by chrisallenlane** [comment]
Thanks for reporting all of this. I'm about to begin a round of improvements and fixes for Windows.

**Comment by chrisallenlane** [comment]
@clach04, thanks again for the detailed and thorough bug report.

Confession: I've been relying on the community for Windows support until now, and had never actually run `cheat` on a Windows environment before personally. I finally purchased a cheap Windows laptop just to test `cheat`, and Windows support was indeed quite a mess.

That said, I believe I have all of this sorted. Please try the [4.2.4][] release, which I published a few moments ago. It's much less painful to use than before.

Also: note that I've only tested this now on a _new_ Windows environment, because as I mentioned above, I didn't have one previously. Please let me know if you encounter any issues upgrading from `4.2.3` to `4.2.4`. I think there's a possibility that there could be some file pathing issues that could arise, though I'm hoping that's not the case.

I'm going to close this as resolved. Feel free to re-open this ticket or to create new tickets as necessary, should you have the need.

Thanks again for your help!

[4.2.4]: https://github.com/cheat/cheat/releases/tag/4.2.4

**Comment by clach04** [comment]
@chrisallenlane a very, very belated thank you and confirmation that Windows works great. Thanks for such a useful tool!
