### ISSUE TITLE
display cheats of a command on Windows

### ISSUE THREAD

**Issue by matt-bc** [cheat/cheat#672]
Hi, 

First thank you for your amazing project.
I don't think this topic has been covered yet, if so, excuse me.

Im on windows, i install cheat and it's works very well, i also install vim to edit some existing cheat.
my problem is just when i am looking for information about the tar command for exemple with: cheat tar

He print to me the result in my shell (powershell or cmd) with so many bad characters like "←[0m←[38;5;242m" at the beginning and at the end of each sentence (see on the picture) 

![Capture](https://user-images.githubusercontent.com/93484329/175549237-72ad3206-66ad-45cc-8599-aed368b41a0b.PNG)

I know that these characters correspond to colors, how can they be supported under windows ? 
I try to add visual: vim on the config.yml file but it doesn't work
The problem is not very annoying, and i can use -e without edit, just to have a better representation

Thx for your next reply

**Comment by chrisallenlane** [comment]
Thanks for reporting this. I'm about to do some work to improve Windows support, so I'll take a look.

**Comment by chrisallenlane** [comment]
Hi, @matt-bc

I published the [4.2.4][] release of `cheat` a few moments ago, which changes some default configuration values (and executable behaviors) to dramatically improve Windows support.

With that said, please do the following:

1. Upgrade to `4.2.4`
2. Within your config file:
  2a. Set `pager` to `more`
  2b. Set `formatter` to `terminal`
  2c. Comment out `style`

I believe that should solve all of your problems.

I'm optimistically going to close this ticket as resolved now, but if the above doesn't fix your issue, please re-open this ticket.

Thanks.

[4.2.4]: https://github.com/cheat/cheat/releases/tag/4.2.4
