### ISSUE TITLE
WANTED: community package maintainers

### ISSUE THREAD

**Issue by chrisallenlane** [cheat/cheat#677]
I added an `INSTALLING.md` file that provides instructions for installing `cheat`:
https://github.com/cheat/cheat/blob/master/INSTALLING.md

That file mentions several [community-maintained packages for various package managers][packages].

If you are maintaining a community package (or know someone who is), please either tell me about it, or (better) open a PR that adds it to the table above.

Note that this file should only contain installation instructions for the "official" `cheat` application, though [links to related and similar applications are welcome in the wiki][wiki].

[packages]: https://github.com/cheat/cheat/blob/master/INSTALLING.md#install-via-package-manager
[wiki]: https://github.com/cheat/cheat/wiki/Related-Projects

**Comment by dotcs** [comment]
There are two packages maintained for Arch Linux in the Arch User Repository (AUR). Both seem to be well maintained and probably be worth to be added to the list.

- [cheat](https://aur.archlinux.org/packages/cheat): Builds executables from source
- [cheat-bin](https://aur.archlinux.org/packages/cheat-bin): Pulls executables directly from GitHub Packages

**Comment by chrisallenlane** [comment]
@dotcs, thanks for these.

I'm not an Arch user. Am I correct that these are the respective commands for installing these packages?

```
pacman -S cheat
pacman -S cheat-bin
```

This is, at least, what the `cheat` community cheatsheets are telling me. lol.

I ask because I've been including this information as well within `INSTALLING.md`. (Perhaps I should not.)

**Comment by dotcs** [comment]
Installing packages from AUR is explained [here](https://wiki.archlinux.org/title/Arch_User_Repository#Installing_and_upgrading_packages). AUR packages are non-official community maintained packages, so the installation is unfortunately not as simple as `pacman -S <name>`. That said, [there is a wrapper around the standard package manager `pacman` available](https://github.com/Jguer/yay) that make installation as easy as `yay -S <name>`.

I think in your docs, it should be sufficient to mention that this is an AUR package and link users to the [documentation](https://wiki.archlinux.org/title/Arch_User_Repository#Installing_and_upgrading_packages) for installation instructions.

**Comment by chrisallenlane** [comment]
@dotcs, thanks for the information. I've included the packages you listed here in the documentation for the `4.3.2` release:

https://github.com/cheat/cheat/releases/tag/4.3.2

I've also simplified the installation instructions, per your suggestion.

Thanks!

**Comment by chrisallenlane** [comment]
I shouldn't have closed this. I'm re-opening this because there are surely more packages out there that should be documented.
