### ISSUE TITLE
New cmd implementation in minimal POSIX sh?

### ISSUE THREAD

**Issue by Kreyren** [cheat/cheat#682]
```shell
#!/usr/bin/env sh
# shellcheck shell=sh # Written to comply with IEEE Std 1003.1-2017 

${CURL:-curl} https://raw.githubusercontent.com/cheat/cheatsheets/master/${1:-tar} 2>/dev/null | ${LESS:-less}
```

Wrote this, do you want to make it into a git repository in this org? I usually use it to get `tldr` on systems which don't have the main thing packaged e.g. GNU Guix

CC @chrisallenlane

**Comment by chrisallenlane** [comment]
I'll decline to create a repo for it in the org, but it's a clever one-liner :+1:
