### ISSUE TITLE
Git submodules as cheatsheet paths don't work any more

### ISSUE THREAD

**Issue by lucascosti** [cheat/cheat#694]
**A description of the problem**

Carries on from the problem reported and fixed in https://github.com/cheat/cheat/issues/690

Mine might be more of an uncommon edge case, so I totally understand if you decide it's unsupported. 🙂 

* I have all [my shell config in a repo](https://github.com/lucascosti/mac-config/tree/main/zsh), with various external [scripts and tools as git submodules in that repo](https://github.com/lucascosti/mac-config/tree/main/zsh/zshscripts).
* The [community cheatsheets repo](https://github.com/cheat/cheatsheets) is one of those submodules. Having the submodule lets me easily use git to keep the community cheatsheets regularly up to date with any changes. With this latest `cheat` change, because the cheatsheet directory contains a [`.git` file](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefgitfileagitfile) (not a directory) for the submodule, it's stopping `cheat` from seeing those files. If delete the `.git` file, it works.
* The content of the `.git` file in the cheatsheets submodule directory is just `gitdir: ../../../.git/modules/zsh/zshscripts/cheatsheets`

**cheat version info**
`4.3.1`

**cheat configuration info**
If your bug pertains to how cheatsheets are loaded and/or displayed, please
paste here the following information:

1. The output of `cheat -d`

`community: /Users/lucascosti/repos/mac-config/zsh/zshscripts/cheatsheets`

2. The contents of your `conf.yml` file

Stored in my repo here: https://github.com/lucascosti/mac-config/blob/d5f62819eb7efcbd9f0dcf8826142686b63eb77e/zsh/zshscripts/miscdotfiles/cheat/conf.yml.

```
---
# The editor to use with 'cheat -e <sheet>'. Defaults to $EDITOR or $VISUAL.
editor: vim

# Should 'cheat' always colorize output?
colorize: true

# Which 'chroma' colorscheme should be applied to the output?
# Options are available here:
#   https://github.com/alecthomas/chroma/tree/master/styles
style: native

# Which 'chroma' "formatter" should be applied?
# One of: "terminal", "terminal256", "terminal16m"
formatter: terminal16m

# The paths at which cheatsheets are available. Tags associated with a cheatpath
# are automatically attached to all cheatsheets residing on that path.
#
# Whenever cheatsheets share the same title (like 'tar'), the most local
# cheatsheets (those which come later in this file) take precedent over the
# less local sheets. This allows you to create your own "overides" for
# "upstream" cheatsheets.
#
# But what if you want to view the "upstream" cheatsheets instead of your own?
# Cheatsheets may be filtered via 'cheat -t <tag>' in combination with other
# commands. So, if you want to view the 'tar' cheatsheet that is tagged as
# 'community' rather than your own, you can use: cheat tar -t community
cheatpaths:

  # Paths that come earlier are considered to be the most "global", and will
  # thus be overridden by more local cheatsheets. That being the case, you
  # should probably list community cheatsheets first.
  #
  # Note that the paths and tags listed below are just examples. You may freely
  # change them to suit your needs.
  - name: community
    path: ~/repos/mac-config/zsh/zshscripts/cheatsheets/
    tags: [ community ]
    readonly: true
```

**Comment by chrisallenlane** [comment]
@lucascosti, thanks for the thorough and detailed bug report :slightly_smiling_face: 

> Mine might be more of an uncommon edge case, so I totally understand if you decide it's unsupported. :slightly_smiling_face: 

This is not a use-case that I had considered, but it seems reasonable enough to me. I'd like to support it if possible.

Let me hack on this a bit. Presumably with a bit more sophistication in place of the current`strings.Contains(path, "git")` check, we should be able to support this.

**Comment by chrisallenlane** [comment]
@lucascosti, I think I've worked this out. If you have the time, would you mind testing the fix on my personal fork here on your machine?

https://github.com/cheat/cheat/pull/697

If you don't have time, don't sweat it. I will otherwise optimistically assume that this will resolve the problem, and will cut a new release this weekend :slightly_smiling_face:

**Comment by chrisallenlane** [comment]
@lucascosti, for your testing convenience, I'm attaching a Darwin executable here so don't have to bother with the build process:

[cheat-darwin-amd64.gz](https://github.com/cheat/cheat/files/9433092/cheat-darwin-amd64.gz)

**Comment by chrisallenlane** [comment]
@lucascosti, scratch that. I got on a roll this morning, and just decided to publish a new release, changes included. I suspect that this will fix the issue, but please do let me know either way:

https://github.com/cheat/cheat/releases/tag/4.3.2

In the meantime, I'll optimistically close this as resolved, but feel free to re-open it if this fix doesn't work.

Thanks.

**Comment by lucascosti** [comment]
@chrisallenlane Thanks so much for the change! 🙇‍♂️ I can confirm that 4.3.2 resolves the issue and `cheat` now works with my community cheatsheets submodule. 🎉

**Comment by chrisallenlane** [comment]
@lucascosti, excellent! Thanks for the confirmation, and again for such a helpful bug report :+1:
