### ISSUE TITLE
safer installer?

### ISSUE THREAD

**Issue by dcsan** [cheat/cheat#714]
**Is your feature request related to a problem? Please describe.**
on install this prompts me to paste random things into a terminal with `wget ...` and then asks for my sudo password.
this trains people to do bad things

**Describe the solution you'd like**
is there a way to make a bit of a safer installer?

**Describe alternatives you've considered**
installing as a guest user?
via brew? not sure if its really much safer but ...
from a git repo with just a single command to view?

**Additional context**
I recall some other tools a bit like this, even homebrew
still it feels really risky.

**Comment by chrisallenlane** [comment]
I understand your concern, but it's only four lines of straightforward bash, and there are other installation methods listed for users who don't want to do this.
