### ISSUE TITLE
Failed to parse front-matter

### ISSUE THREAD

**Issue by GRNL** [cheat/cheat#717]
I recently moved to an M1 Apple Silicon laptop, and reinstalled cheat from scratch. When calling one of the cheatsheets, I get the following error:
`failed to list cheatsheets: failed to load cheatsheets: failed to load sheet: ip, path: /Users/<user>/.config/cheat/cheatsheets/community/ip, err: failed to parse front-matter: failed to unmarshal frontmatter: yaml: unmarshal errors: line 1: cannot unmarshal !!str tags [ ... into sheet.frontmatter`

**Version info**
`➜ cheat -v
4.4.0`

**Configuration info**
`➜ cheat -d
community: /Users/<user>/.config/cheat/cheatsheets/community
personal:  /Users/<user>/.config/cheat/cheatsheets/personal`

➜ grep -v '#' ~/.config/cheat/conf.yml
editor: vim
colorize: true
style: monokai
formatter: terminal16m
pager: less -FRX
cheatpaths:
  - name: community
    path: /Users/<user>/.config/cheat/cheatsheets/community
    tags: [ community ]
    readonly: true
  - name: personal
    path: /Users/<user>/.config/cheat/cheatsheets/personal
    tags: [ personal ]
    readonly: false

**Comment by faelin** [comment]
@GRNL – I resolved this issue by running

```
cd ~/.config/cheat/cheatsheets
rm -rf community
git clone https://github.com/cheat/cheatsheets.git community
```

**Comment by GRNL** [comment]
Thanks @faelin!

**Comment by loway1994** [comment]
> @GRNL – I resolved this issue by running
> 
> ```
> cd ~/.config/cheat/cheatsheets
> rm -rf community
> git clone https://github.com/cheat/cheatsheets.git community
> ```

Thanks, it works.
