### ISSUE TITLE
Magic SysRq REISUB

### ISSUE THREAD

**Issue by BarbzYHOOL** [cheat/cheat#732]
Could be nice to add this one.

Here is a little tutorial I edited if anyone wants to get inspired from (I've only used REISUB once for now)

----------

# Magic SysRq

## Enable

First of all, ensure Magic SysRq is enabled:

`cat /proc/sys/kernel/sysrq`

0 means `disabled`, 1 means `everything enabled` and >1 is a bitmask of allowed keys. If you are using Ubuntu, you can modify the /etc/sysctl.d/10-magic-sysrq.conf file to set this value at boot time.

## Usage

You invoke SysRq by hitting `Alt + SysRq + Letter` on your keyboard. If you can’t find the `SysRq` key on your keyboard, it is usually the same as the `Print Screen` key.

If your Linux computer is acting crazy and you want to safely reboot it, this is the mnemonic to remember: `Raising Elephants Is So Utterly Boring`:

    R: unRaw (take control of the keyboard back from X)
    E: tErminate (send SIGTERM to all processes)
    I: kIll (send SIGKILL to all processes except init)
    S: Sync (flush filesystem buffers)
    U: Unmount (remount all filesystems read-only)
    B: reBoot

Another good key to keep in mind is `f`. This calls oom_kill() which finds and kills a `big` process in order to give back some RAM to your system. If your system is slowing to a crawl, this is something that can save your skin.

**Comment by chrisallenlane** [comment]
I appreciate the effort, but the scope of this repository is the `cheat` executable, rather than cheatsheet content.
