### ISSUE TITLE
Update chroma dependency

### ISSUE THREAD

**Issue by Samasaur1** [cheat/cheat#735]
**Is your feature request related to a problem? Please describe.**
I was trying to use the catppuccin themes defined in Chroma, but the version of Chroma used by cheat is out of date

**Describe the solution you'd like**
Update the dependency on Chroma from v0.10.0 to v2.8.0

**Describe alternatives you've considered**
Limit the use of themes to those defined in Chroma 0.10.0

**Additional context**
Tickets such as #638 suggest that you can add custom colors by getting them included in Chroma, but unless the Chroma dependency is updated, even doing this won't help.

**Comment by chrisallenlane** [comment]
@Samasaur1, thanks for bringing this to my attention. I didn't realize I wasn't on the current major version.

I just updated to `v2` and merged to `master`. That change will be included in the `4.4.2` release, which will go out today or tomorrow. That said, I'm going to close this as resolved.

Thanks again.
